#### Habitats fauniques

La classification des habitats faunique provient d'une base de donéées fournissant la localisation des 11 habitats fauniques légaux selon la définition du Règlement sur les habitats fauniques et situés en terres du domaine de l'État. Ces 11 types d'habitats sont les suivants :

- Habitat du poisson
- Aire de concentration d’oiseaux aquatiques
- Héronnière
- Île ou presqu’île habitée par une colonie d’oiseaux
- Aire de confinement du cerf de Virginie
- Aire de fréquentation du caribou au sud du 52e parallèle
- Habitat du rat musqué
- Vasière
- Habitat d’une espèce faunique menacée ou vulnérable
- Falaise habitée par une colonie d’oiseaux
- Aire de mise bas du caribou au nord du 52e parallèle

La base de donnée a été considérée de façon intégrative en tant qu'habitat unique représentant des habitats fauniques d'importance identifiés par le gouvernement provincial.

WARNING: Considérer retirer cette base de données et cet habitat de l'analyse. Difficile à justifier et à caractériser.
