#### Milieux humides

Les milieux humides abritent une forte richesse faunique et floristique, fournissent un habitat crucial au cours du cycle de vie de multiples espèces, et sont des habitats essentiels pour plusieurs espèces en péril. Les milieux humides regroupent une diversité importante de différents types d'habitats, dont les étangs, les marais, les marécages et les tourbières. La cartographie des milieux humides utilisés pour notre étude est le résultat de l'intégration de trois bases de données. La première provient de Canards Illimités Canada et correspond à une cartographie des milieux humides des basses-terres du Saint-Laurent, de la plain du Lac Saint-Jean et d'autres secteurs au sud du Québec [@canards2020]. La deuxième base de données provient de l'Atlas des milieux côtiers d’intérêt pour la conservation dans l’estuaire et le golfe du Saint-Laurent qui est également utilisée pour caractériser les marais côtiers [@jobin2019; @psl2020]. La troisième base de données provient d'un Atlas similaire développé pour identifier des territoires d'intérêt pour la conservation dans les basses-terres du Saint-Laurent [@jobin2019b; @psl2019]. Puisqu'un chevauchement spatial existe entre ces trois bases de données, nous avons fusionné l'ensemble des sites qui les constituent afin d'obtenir une seule base de données intégrative pour les milieux humides au sein de la zone d'étude. Cette base de données intégrative a ensuite été incorporée à la grille d'étude.
