##### Frayères et aires d'alevinage

Les frayères sont des milieux essentiels au maintien de populations de poissons; en effet, des perturbations à ces sites, ou au comportement des espèces pendant la période de fraie, peuvent avoir des impacts majeurs sur la dynamique des populations de poissons. Similairement, les sites d'alimentation et de protection pour les stades de vie initiaux des poissons (*e.g.* larves, alevins, juvéniles), qui sont beaucoup plus susceptibles aux effets de perturbations à leur habitat. Ces sites, nommés aires d'alevinage, sont ainsi essentiels à leur survie.  La protection des frayères et des aires d'alevinage est ainsi d'une importance majeure puisqu'ils constituent un goulot d'étranglement pour la dynamique des populations de poissons.

Les données utilisées pour caractériser les frayères et les aires d'alevinage proviennent d'un exercice d'intégration de données d'observation *in situ* couvrant la période de 1974 à 2019 (Tableau \@ref(tab:frayerealevinage)). Les frayères et aires d'alevinage identifiées regroupent des données pour 71 et 49 espèces de poissons et couvrent une superficie d'environ 275 et 230 $km^2$ au sein de la zone d'étude, respectivement. Les données regroupent des frayères et des aires d'alevinage confirmées ou potentielles lorsque les habitats étaient jugés propices à la fraie ou l'alevinage des poissons. Il est donc probable que ces données soient partielles et ne devraient être considérées comme un portrait exhaustif des frayères et des aires d'alevinage dans la zone d'étude. Les données sont composées de points et de polygones. Nous avons ajouté une zone tampon de 100 $m$ autour des points, puis avons intégré la présence de frayères au sein de notre grille d'étude de 1 $km^2$.

<br/>

```{r frayerealevinage}
tab <- as.data.frame(meta$dataDescription$frayere_alevinage)
tab <- arrange(tab, Source)
tab$Superficie_frayere <- round(tab$Superficie_frayere, 2)
tab$Superficie_alevinage <- round(tab$Superficie_alevinage, 2)

tab %>%
  knitr::kable(
    col.names = c("Source", "Nombre de frayères", "Superficie des frayères $km^2$", "Nombre d'aires d'alevinage","Superficie des aires d'alevinage $km^2$"),
    row.names = FALSE,
    caption = "Sources utilisées pour caractériser les frayères et les aires d'alevinage dans la zone d'étude."
  )
```

<br/>
