#### Marais côtiers

La caractérisation des marais côtiers provient de l'Atlas des milieux côtiers d’intérêt pour la conservation dans l’estuaire et le golfe du Saint-Laurent [@jobin2019; @psl2020]. L'objectif de cet atlas était d'identifier des sites où des mesures de conservation sont jugées criants. Plusieurs attributs du territoire y sont décrits afin d'effectuer l'identification de ces sites. Une couche de données décrivant les marais côtiers y est intégrée. Les marais côtiers, tels que décrit au sein de l'Atlas, intègre la distribution de marais salés et de marais saumâtres dans l'estuaire et le golfe du Saint-Laurent. Ces habitats sont généralement reconnus pous leur riche diversité en espèces fauniques et floristiques, contribuent à purifier les cours d'eau et protègent les berges contre l'érosion [@jobin2019]. 


<!--
Jobin 2019:
> L’intérêt écologique et faunique des marais côtiers est lié à une vaste gamme d’habitats riches, diversifiés et de grande qualité (Tremblay, 2002). Plusieurs ont été définis comme des zones d’importance pour la conservation des oiseaux (ZICO); ce sont des sites renommés pour les colonies de sternes et de goélands, les rassemblements de sauvagines et la présence du râle jaune (Coturnicops noveboracensis), du hibou des marais (Asio flammeus) et du bruant de Nelson. En plus d’être très riches sur le plan de la faune aviaire, ces marais côtiers sont des endroits de prédilection pour plusieurs espèces de poissons et de mollusques et certains hébergent des sites cruciaux pour le maintien des populations du satyre fauve des Maritimes (Coenonympha nipisiquit), une espèce de papillon en voie de disparition au Canada (Environnement Canada, 2012). Les estuaires et les marais salés sont considérés comme l’habitat estival préféré du bar rayé (Morone saxatilis), de l’anguille d’Amérique (Anguilla rostrata) et du saumon atlantique qui utilisent ces milieux comme aire d’alimentation et de transition entre les séjours en mer et la période de fraie en rivière (Monticone et coll., 2015).

> En plus d’offrir des habitats importants pour plusieurs espèces fauniques et floristiques, ces milieux jouent un rôle primordial dans la purification de l’eau et la protection des rivages contre l’érosion. Plusieurs milieux humides côtiers ont d’ailleurs été déterminés comme étant d’intérêt pour la conservation dans différents plans de conservation. Par exemple, sur la rive nord du Saint-Laurent, le marais salé de la Pointe-aux-Outardes est reconnu comme d’importance pour la conservation, tout comme le sont les immenses marais salés de la baie de L’Isle-Verte et de Kamouraska sur la rive sud (CIC, 2019; Pelletier-Gilbert et coll., 2011) et le barachois de Malbaie dans la baie des Chaleurs (Monticone et coll., 2015).
-->
