# Démarche

Plusieurs ouvrages provenant de la littérature scientifique et de la littérature grise[^grise] détaillent les différentes étapes d’une évaluation d’impacts cumulés [*e.g.* @hegmann1999]. L’équipe de Transport Canada a travaillé, au cours des dernières années, avec plusieurs experts Canadiens et à l’international sur la démarche à adopter afin d’évaluer les impacts cumulés des activités maritimes [*e.g.* @lerner2018; @pickard2019]. En plus de l’importance des processus de concertation et de consultation des communautés autochtones et non autochtones, et des parties prenantes, une évaluation d’effets cumulés inclut généralement les étapes suivantes, sans toutefois s’y limiter:


<!--
Éventuellement utiliser un schéma conceptuel qui inclue également les
consultations avec les comunautés locales et autochtones
-->

1. Identifier, impliquer et communiquer avec les parties prenantes de l’évaluation (p.ex. communautés autochtones et non autochtones), et ce à toutes les étapes de la démarche

2. Définir la portée de l’évaluation
    * Établir les objectifs de l’évaluation
    * Définir les limites spatiales et temporelles de la zone à l’étude
    * Identifier les activités préoccupantes et les facteurs de stress qui en découlent
    * Identifier et prioriser les composantes valorisées sur lesquelles l’évaluation doit être effectuée

3. Établir un portrait de la zone à l'étude
    * Caractériser l'intensité, l'étendue et la fréquence des activités et
      facteurs de stress.
    * Caractériser les composantes valorisées
    * Évaluer la vulnérabilité des composantes valorisées aux facteurs de stress

4. Analyse des effets cumulés

5. Diagnostic de l'analyse
    * Répartition spatiale des effets cumulatifs
    * Exploration détaillée de l’effet des facteurs de stress sur les composantes valorisées
    * Identifier les sources d’incertitude et les lacunes en connaissances

6. Mise en place de processus décisionnels
    * Identifier et mettre en place des mesures de gestion
    * Identifier des mesures d'atténuation et de compensation

7. Suivi et gestion adaptative

L’identification et l’implication des parties prenantes (1) et la définition de la portée de l’évaluation (2) a déjà été effectuée au préalable à travers plusieurs séances de concertation et d’atelier de travail avec des experts dans le domaine et divers parties prenantes. À la lumière de ces processus, nous nous concentrons maintenant sur le portrait de la zone à l’étude (3), l’analyse des effets cumulatifs (4) et l’évaluation critique de l’analyse (5). Les étapes 6 et 7 ne font pas partie de ce contrat.

[^grise]: La littérature grise correspond à des documents produits par des par diverses instances publiques, commerciales ou industrielles, soumis aux règles de la propriété intellectuelle, et non contrôlés par le processus de révision par les pairs scientifique.
