# Portée {#portee}

L’évaluation des impacts cumulatifs des activités maritimes sera effectuée pour les écosystèmes du Saint-Laurent (tronçon fluvial et estuaire, i.e. de Montréal à Pointe-des-Monts) et du Saguenay (partie en eau profonde jusqu’à Saint-Fulgence). Le processus d’évaluation permettra d’établir un portrait de la répartition spatiale des [composantes valorisées](#cv) et des [facteurs de stress](#stress) issus des activités maritimes de la zone d’étude ciblés pour l’analyse. Les activités maritimes incluent non seulement les navires commerciaux, mais aussi les bateaux de croisières, traversiers, bateaux de pêche, plaisanciers. Les infrastructures portuaires ne sont pas incluses dans ce projet. La vulnérabilité de composantes valorisées aux divers facteurs de stress sera ensuite évaluée. Enfin, le portrait de la zone d’étude sera utilisé afin d’effectuer l’évaluation des effets cumulés des activités maritimes sur les composantes valorisées ciblées. Cette étude vise une gestion plus proactive et holistique des écosystèmes marins et dulcicoles.

La [méthode d’analyse des effets cumulés](#ic) et les [étapes de la démarche](#etapes) permettront d’obtenir un portrait géographique contemporain de la zone d’étude, des sources de pression liées au trafic maritime et des composantes valorisées jugées prioritaires. Ce portrait structurera les connaissances disponibles au sein de la zone d’étude. Ces connaissances pourraient permettre de bonifier le projet pilote de Transport Canada et d’effectuer des analyses d’effets cumulés récurrentes, d’explorer de nouvelles questions de gestion, et d’élargir la portée de l’étude afin d’inclure des secteurs d’activités additionnels et d’accroître la superficie de la zone d’étude.

La collaboration avec les Premières Nations et l’intégration du savoir autochtone seront priorisés lors de la démarche. Les discussions et conclusions issus des ateliers de travail avec les représentants des Premières Nations et autres parties prenantes pour l’élaboration du projet seront des atouts majeurs pour le processus d’évaluation des effets cumulés. Les savoirs autochtones, lorsque disponibles, seront utilisés afin de détecter les changements dans le milieu et pour améliorer notre compréhension des effets cumulatifs.
