# Calendrier

| Livrable | Date |
| :------------------------------- | :------------- |
| Lancement et préparation du calendrier et du plan de travail | 	Début février 2020 |
| Document présentant un aperçu de la méthode	| Mi-mai 2020 |
| Établir liste de besoins en termes de données et initier les contacts visant à obtenir les données nécessaires	| Mi-mars - mai 2020 |
| Webinaire avec partenaires et collaborateurs | Mai 2020 |
| Ajuster approche selon les commentaires des collaborateurs | Mai-Juin 2020 |
| Contacts et collecte de données	| Juin 2020 - Mars 2021 |
| Cartographie des sources de stress et des composantes valorisées | Juillet 2020 - Mars 2021 |
| Évaluation préliminaire de l’exposition cumulée des composantes valorisées aux stresseurs environnementaux	| Novembre 2020 - Février 2021 |
| Évaluation préliminaire de la vulnérabilité des composantes valorisées | Novembre 2020 - Février 2021 |
| Rapport sommaire et présentation des constations préliminaires aux fins de commentaires lors d’un atelier, révision et échanges sur la vulnérabilité des composantes valorisées et échanges sur la cartographie des sources de stress et des composantes valorisées | Mars 2021 |
| Ajuster approche selon les commentaires des collaborateurs, intégration de nouvelles considérations et intégration des connaissances des collaborateurs et des Premières Nations à l’évaluation de la vulnérabilité des composantes valorisées | Avril - Mai 2021 |
| Contacts et collecte de données manquantes ou proposées lors de l’atelier de mars 2021	| Avril - Mai 2021 |
| Analyses finales et rédaction du rapport | Mai 2021 - Décembre 2021 |
| Livraison du rapport final aux fins de traduction et de diffusion	|	31 décembre 2021 |
| Présentation du rapport final lors d’un atelier	| Début février 2022 |
