# Collecte et gestion des données

## Collecte

La collecte des données a été effectuée en collaboration avec les différentes parties prenantes du projet ainsi qu'avec la collaboration et le soutien de Transport Canada et les membres du projet porté par le Plan d’action Saint-Laurent. Aucune nouvelle donnée n'a été récoltée pour cette évaluation, puisqu'elle se base sur des données déjà existantes permettant de caractériser la répartition spatiale des composantes valorisées et des facteurs de stress au sein de la zone d'étude, ainsi que la vulnérabilité des composantes valorisées aux facteurs de stress. Une attention particulière a été attribuée aux connaissances détenues par des experts disciplinaires, ainsi que par les communautés autochtones et non-autochtones. Nous avons ainsi échangé directement avec des personnes ressources afin de réviser les différentes sections du portrait de la zone d'étude caractérisant les stresseurs environnementaux et les composantes valorisées. Les personnes ressources ayant contribué à la révision de ces sections sont d'ailleurs remercié spécifiquement au début des sections auxquelles elles ont contribué. Une liste des personnes ou organismes ressources consultés pour ce projet est disponible à l'Annexe 1. Une liste de l'ensemble des données considérées pour l'évaluation est disponible à l'Annexe 2, ainsi qu'une description plus détaillée à l'Annexe 3.

Discuter de l'approche itérative, et de l'utilisation de bases de données ouvertes du gouvernement fédéral et provincial, et de l'OGSL

La collaboration avec les Premières Nations et l’intégration du savoir autochtone seront priorisés lors de la démarche. Les discussions et conclusions issus des ateliers de travail avec les représentants des Premières Nations et autres parties prenantes pour l’élaboration du projet seront des atouts majeurs pour le processus d’évaluation des effets cumulés. Les savoirs autochtones, lorsque disponibles, seront utilisés afin de détecter les changements dans le milieu et pour améliorer notre compréhension des effets cumulatifs.
