# Collecte et gestion de données

La collecte des données sera effectuée en collaboration avec les différentes parties prenantes du projet ainsi qu’avec la collaboration et le soutien de Transport Canada et les membres du projet porté par le Plan d’action Saint-Laurent. Aucune nouvelle donnée ne sera récoltée pour cette évaluation. L’entièreté de l’étude est ainsi dépendante de la disponibilité des données permettant de caractériser la répartition spatiale des composantes valorisées et des facteurs de stress, ainsi que la vulnérabilité des composantes valorisées aux facteurs de stress. Une attention particulière sera attribuée aux connaissances détenues par les communautés autochtones et non-autochtones. À cet égard, nous prévoyons une rencontre avec des représentants des Premières Nations suite à la présentation de l’approche méthodologique afin de mettre en place une stratégie adéquate qui nous permettra de valoriser leurs savoirs et intégrer leurs préoccupations. L’approche de travail adoptée permettra un processus itératif et transparent permettant l’intégration de nouvelles considérations ou d’ajustement de considérations préalablement partagées suite aux processus de concertation. Il est à noter que les préoccupations des Premières Nations, des communautés côtières et des diverses parties prenantes du projet ont également été considérées en amont de la présente étude à travers divers processus de mobilisation organisés par l’équipe de Transports Canada.

La gestion des bases de données sera assurée par l’équipe de l’Université Laval de travail et visera à assurer une transparence complète du travail effectué. Dans la mesure du possible, notre équipe a pour objectif le partage complet du code et des données utilisées pour toutes les étapes du processus d’évaluation d’impacts cumulés. Les données de nature sensible pourront tout de même faire l’objet d’embargos ou d’ententes de partage plus strictes limitant ou bloquant entièrement l’accessibilité à certains types de données. Il demeure tout de même possible d’intégrer ce type de données à un processus ouvert en les cataloguant convenablement afin qu’un utilisateur puisse minimalement connaître le type et la provenance des données utilisées au sein des analyses, ainsi que les contacts pertinents permettant d’obtenir davantage d’informations sur ces dernières. Toutes suggestions, recommandations ou requête des différents partenaires quant à la collecte, la gestion et le partage des données seront considérées afin d’assurer une collaboration efficace et respectueuse.

En plus des rencontres et des séances de mobilisation prévues au contrat et visant une collaboration étroite avec les responsables de Transport Canada, nous adopterons une approche transparente et reproductible similaire à celle que nous utilisons pour notre initiative de caractérisation des facteurs de stress au sein de l’estuaire et du golfe du Saint-Laurent nommée
<a href="https://david-beauchesne.shinyapps.io/edriversapp/" target="_blank"><i>eDrivers</i></a>.  Nous basons notre approche sur les principes
<a href="https://ogsl.ca/fr/principes-fair" target="_blank"><i>FAIR</i></a>
(Findable, Accessible, Interoperable, Reusable), qui visent à s’assurer que les données utilisées soient découvrables, accessibles, interopérables et réutilisables. Nous utilisons ainsi des outils de programmations, notamment le langage
<a href="https://www.r-project.org/" target="_blank"><i>R</i></a>[^r].
L’utilisation d’outils de programmation, à l’instar de logiciels comme
<a href="https://www.arcgis.com/index.html" target="_blank"><i>ArcGIS</i></a>[^arc],
 offre plusieurs avantages. Ils offrent une grande souplesse permettant l’intégration de changements ou de nouvelles considérations très rapidement sans devoir refaire plusieurs étapes d’un processus complexe. Cette souplesse ne se limite pas aux analyses, puisque l’ensemble des étapes d’un projet, de l’intégration des données brutes à la production de rapports, peuvent être intégrées et ainsi facilement modifiées. Il devient alors aisé d’intégrer des commentaires ou de nouvelles recommandations suite à des processus de mobilisation, par exemple. Nous utiliserons également
 <a href="https://github.com/" target="_blank"><i>GitHub</i></a>[^git],
un outil de contrôle de version qui permettra la documentation, le contrôle de
la qualité et l’historique du développements et des modifications des éléments
de programmation pertinents à l’ensemble du projet.

[^r]: R est un logiciel libre destiné aux statistiques, la science des données et les graphiques (https://www.r-project.org/)
[^arc]: ArcGIS est une suite de logiciels d'information géographique (SIG) développés par la société américaine Esri (https://www.arcgis.com/index.html)
[^git]: GitHub est un service web d'hébergement et de gestion de développement de logiciels utilisé par plus de 40 millions d'utilisateurs partout à travers le monde (https://github.com/).
