### Ancrages

```{r ancrage_setup, echo = FALSE}
meta <- read_yaml("../data/data-metadata/int_st_ancrage.yml")
```

Les sites d'ancrage ont été caractérisés grâce à une base de données provenant de la Garde Côtière Canadienne [@gcc2019]. Une [version accessible ouvertement](https://ouvert.canada.ca/data/fr/dataset/622a7f72-4a00-4f9e-b04f-af6551c77db3) est également disponible sur le portail de données ouverte du Gouvernement du Canada, mais cette ressource était moins complète que celle disponible par la Garde Côtière Canadienne. Cette dernière fournit la localisation de l'ensemble des sites d'ancrage pour l'est du Canada. Un total de `r meta$dataDescription$observations$total` sites y sont répertoriés au sein de la zone d'étude. Pour caractériser l'intensité de ce stresseur environnemental, une zone tampon de 2 $km$ a été tracée autour de chaque site d'ancrage. Le nombre de sites d'ancrage qui intersecte chaque cellule de la grille d'étude a ensuite été évalué afin d'obtenir une évaluation du nombre de sites ayant le potentiel d'influencer une cellule en $n$ sites * $km^{-2}$. Cette caractérisation permet d'obtenir une évaluation du risque environnemental associé aux sites d'ancrage au sein de chaque cellule de la grille d'étude en assumant que les risques sont supérieurs lorsque plusieurs sites d'ancrage sont situés à proximité.
