# Remerciements {-}

D'abord et avant tout, nous tenons à remercier toutes les personnes et organismes ayant contribué à façonner ce projet pilote par leur présence aux ateliers de concertation qui ont mené à l'identification des stresseurs environnementaux et des composantes valorisées sélectionnées pour cette étude et aux webinaires organisés pendant la durée du projet. Ces échanges ont permis de définir non seulement les objectifs de ce projet, mais également d'orienter les deux dernières années de travail menées par notre équipe de recherche. 

Nous remercions également les Premières Nations ayant participé à cette étude pour leur présence aux activités de concertation, les échanges soutenus avec notre équipe de recherche et le partage de données et de savoirs. Cette implication fut d'une importance cruciale pour l'atteinte des objectifs de l'étude. Nous désirions entreprendre les échanges avec les Premières Nations avec humilité et écoute et c'est avec humilité et écoute que nous espérons poursuivre ces échanges dans le futur. 

Nous désirons également remercier tous les collaborateurs et organismes ayant échangé avec notre équipe tout au long du projet. Votre ouverture et votre volonté de partager vos connaissances sont nécessaires à la gestion écosystémique en général et à l'évaluation des effets cumulatifs en particulier; sans votre travail, le nôtre serait impossible. Certains de ces collaborateurs sont remerciés directement au sein des sous-sections du [portrait de la zone d'étude](#portrait) du rapport; d'autres sont identifiés au sein de l'[annexe 2](#annexe2). Cet annexe compte d'ailleurs plus de 60 personnes ressources et organismes ayant contribué par des échanges et des données ou en diffusant des données sur diverses plateformes de données ouvertes.

Nous remercions également les membres du Plan d'action Saint-Laurent sur le projet *Établir un cadre  commun d'évaluation des effets cumulatifs des activités maritimes sur le Saint-Laurent/Saguenay*; vos commentaires et nos échanges ont permis d'améliorer notre rapport jusqu'à la toute fin. Nous espérons sincèrement que notre évaluation vous sera utile et qu'elle sera une source de motivation et d'inspiration pour poursuivre et diversifier vos efforts au sein du Saint-Laurent. 

Finalement, un merci spécial à Catherine Guillemette, Transport Canada, sans qui ce projet n'aurait pu exister. Simplement, ton travail a pu connecter un réseau remarquable d'acteurs du milieu diversifié et investi dans une vision de gestion intégrative de nos écosystèmes. Mais surtout, c'est ton écoute et ton ouverture qui ont pu transformer ce projet en une aventure ayant un point de départ clair mais un fil d'arrivée à découvrir. Peu de gestionnaires de projet possèdent cette capacité d'adapter leurs objectifs et leurs attentes en cours de projet et nous sommes reconnaissants d'avoir eu la chance de travailler étroitement avec toi. Maintenant, nous ne pouvons qu'espérer que tu continueras de travailler sur des projets rassembleurs; les défis sociaux et environnementaux de demain auront besoin d'ambassadrices comme toi!