# Introduction


## Démarche

L’équipe de Transport Canada a travaillé, au cours des dernières années, avec plusieurs experts Canadiens et à l’international sur la démarche à adopter afin d’évaluer les effets cumulatifs des activités maritimes [*e.g.* @lerner2018; @pickard2019]. En plus de l’importance des processus de concertation et de consultation des communautés autochtones et non autochtones, et des parties prenantes, une évaluation d’effets cumulés inclut généralement les étapes suivantes, sans toutefois s’y limiter:


1. Identifier, impliquer et communiquer avec les parties prenantes de l’évaluation (p.ex. communautés autochtones et non autochtones), et ce à toutes les étapes de la démarche

2. Définir la portée de l’évaluation
    * Établir les objectifs de l’évaluation
    * Définir les limites spatiales et temporelles de la zone à l’étude
    * Identifier les activités préoccupantes et les facteurs de stress qui en découlent
    * Identifier et prioriser les composantes valorisées sur lesquelles l’évaluation doit être effectuée

3. Établir un portrait de la zone à l'étude
    * Caractériser l'intensité, l'étendue et la fréquence des activités et
      facteurs de stress.
    * Caractériser les composantes valorisées
    * Évaluer la vulnérabilité des composantes valorisées aux facteurs de stress

4. Analyse des effets cumulés

5. Diagnostic de l'analyse
    * Répartition spatiale des effets cumulatifs
    * Exploration détaillée de l’effet des facteurs de stress sur les composantes valorisées
    * Identifier les sources d’incertitude et les lacunes en connaissances

6. Mise en place de processus décisionnels
    * Identifier et mettre en place des mesures de gestion
    * Identifier des mesures d'atténuation et de compensation

7. Suivi et gestion adaptative

L’identification et l’implication des parties prenantes (1) et la définition de la portée de l’évaluation (2) ont été définis en amont du déclenchement des travaux présentés au sein de ce rapport à travers divers processus de concertation, de mobilisation et d'ateliers de travail organisés par l'équipe de Transports Canada. Ces processus ont permi de considérer les préoccupations des Premières Nations, des communautés côtières et de diverses parties prenantes du projet en vue d'établir la portée de l'évaluation des effets cumulatifs des activités maritimes dans la zone d'étude, *i.e.* d'identifier le stresseurs environnementaux et les composantes valorisées à considérer pour l'évaluation. À la lumière de ces processus, le projet pilote présenté par ce rapport se concentre sur le portrait de la zone à l’étude (3), l’analyse des effets cumulatifs (4) et l’évaluation critique de l’analyse (5). Les étapes 6 et 7 ne font pas partie de cette évaluation. Les prochaines sections du rapport présentent les étapes couvertes par le projet pilote.
