# Contexte

Transports Canada élabore et applique des politiques et des règlements pour faire progresser la sécurité et la sûreté du système de transport maritime du Canada. Le Ministère favorise un réseau efficace et durable qui protège l’environnement maritime et contribue au développement économique.

En novembre 2016, le Gouvernement du Canada a annoncé le Plan de protection des océans (PPO) au montant de 1,5 milliard de dollars ayant pour objectif d’améliorer la sécurité maritime et la navigation responsable, de protéger le milieu marin canadien et d’offrir de nouvelles possibilités pour les Canadiens.

Grâce à ce plan, le Gouvernement du Canada est résolu à conserver et à restaurer les écosystèmes marins côtiers qui sont vulnérables à l’augmentation du trafic maritime, tout en réduisant l’incidence du trafic maritime quotidien. De nombreuses préoccupations ont été exprimées concernant l’augmentation du transport maritime et l’impact des autres activités maritimes (un secteur d’activités pouvant être une source importante d’impacts anthropiques) sur les écosystèmes côtiers et maritimes ainsi que sur le mode de vie des communautés autochtones.

Pour répondre à ces préoccupations, Transports Canada collabore avec les Premières Nations, les intervenants de l’industrie maritime et les collectivités côtières depuis 2017 par l’organisation d’ateliers collaboratifs pour faire en sorte que toutes les parties soient impliquées tout au long du projet.

En parallèle, un projet portant sur le développement d’un cadre commun d’évaluation des effets cumulatifs des activités maritimes sur le Saint-Laurent a été initié sous le Plan d’action Saint-Laurent en 2018.  Ce projet vise entre autres à assurer la coordination entre le Gouvernement du Canada (Transports Canada, Pêches et Océans Canada, Garde Côtière Canada et l’Agence d’évaluation d’impact du Canada) et le Gouvernement du Québec (ministère de la Sécurité publique, ministère des Forêts, de la Faune et des Parcs et ministère de l'Environnement et de la Lutte contre les changements climatiques) dans la collecte et le regroupement de données existantes et requises à l’étude tout en encourageant une étroite collaboration avec les Premières Nations, les intervenants maritimes et les collectivités côtières.

Dans ce contexte, Transports Canada a mis en place un projet pilote visant à effectuer une analyse des effets cumulatifs des activités maritimes dans le Saint-Laurent (tronçon fluvial et estuaire) et dans la rivière Saguenay (partie en eau profonde) au Québec. L’objectif de ce projet pilote est de gérer la façon dont les effets des activités maritimes, en particulier, agissent cumulativement sur l’environnement humain et biophysique. Les activités maritimes incluent non seulement les navires commerciaux, mais aussi les bateaux de croisières, traversiers, bateaux de pêche, plaisanciers. La localisation, l’intensité et/ou le mouvement de ces divers type d’embarcations peuvent imposer un ou plusieurs facteurs de stress aux écosystèmes. Les infrastructures portuaires ne sont pas incluses dans ce projet. En tant que tel, ce projet pilote constitue une approche d'évaluation des effets cumulatifs sectorielle qui vise à examiner les questions et les effets environnementaux se rattachant à un secteur particulier (c.-à-d. un cadre axé sur l’évaluation d’un seul secteur d’activités).

Ce contrat appuiera le Gouvernement du Canada et le Gouvernement du Québec dans la conception d’un cadre commun d’évaluation des effets cumulatifs des activités maritimes; et permettra d’identifier des outils et des stratégies d’atténuation pouvant s’appliquer aux déplacements actuels de navires et au développement de projets futurs. Le tout sera effectué de façon collaborative avec les Premières Nations, les scientifiques de diverses provenances et les organismes de réglementation, afin de prendre des décisions fondées sur les éléments les plus probants.
