# Summary {-}

```{r sommairesetup, echo = FALSE}
st <- read.csv("../data/data-metadata/metadata_stresseurs.csv")
cv <- read.csv("../data/data-metadata/metadata_composantes_valorisees.csv")
st$stresseur <- gsub("_","",st$stresseur)
cv$comp_val <- gsub("_","",cv$comp_val)

src <- function(dat) {
    paste(dat$source, collapse = ",") %>%
    str_split(",") %>%
    unlist() %>%
    unique() %>%
    length()
}

ct1 <- function(dat) {
  dat %>%
  group_by(title, stresseur) %>%
  summarize(tot = n()) %>%
  apply(., 1., function(x) glue("[{x[1]}](#{x[2]}) ({x[3]})")) %>%
  gsub("\\( ", "\\(", .) %>%
  paste(collapse = "; ") %>%
  tolower()
}

ct2 <- function(dat) {
  dat %>%
  group_by(title, comp_val) %>%
  summarize(tot = n()) %>%
  apply(., 1., function(x) glue("[{x[1]}](#{x[2]}) ({x[3]})")) %>%
  gsub("\\( ", "\\(", .) %>%
  paste(collapse = "; ") %>%
  tolower()
}
```

Through the St. Lawrence action plan, the Government of Canada and the Government of Quebec have been collaborating since 2018 on a common framework for the assessment of the cumulative effects of marine vessel activities on the St. Lawrence and Saguenay River, working closely with First Nations, various stakeholders and coastal communities. A team from Laval University was mandated for a pilot assessment of cumulative effects. The [objective](#objectifs) of the pilot project was to propose and test a cumulative effects assessment approach in a [study area](#zoneetude) that covers the St. Lawrence (fluvial section and estuary) and the Saguenay River (deep water section). This pilot project is centered on the assessment of the cumulative effects of [7 environmental stressors](#stintro) originating from marine vessel activities on [5 valued components](#cvintro) identified beforehand through consultation workshops with relevant experts, collaborators, and stakeholders. 

The [method](#methode) selected to assess the [cumulative effects](#sectioncea) of marine vessel activities in the study area comes from @halpern2008a and requires three types of data: 1) [the spatial presence or absence of valued components](#cvmethod), 2) [the spatial distribution and relative intensity of environmental stressors](#strmethod), and 3) [the relative vulnerability of each valued component to each stressor](#vulnmethod). The proposed method combines those three elements to obtain a [cumulative effects score that is relative and spatially explicit](#ceamethod).

The process of gathering the necessary data to apply this cumulative effects approach is referred to, in this report, as the [portrait](#portrait) of the study area. The characterization of [environmental stressors](#strportrait) was done through the integration of `r src(st)` datasets and results in the description of `r length(unique(st$title))` stressors divided in `r nrow(st)` subcategories: `r ct1(st)`. The characterization of [valued components](#cvportrait), meanwhile, was done through the integration of `r src(cv)` datasets and resulted in the description of `r length(unique(cv$title))` valued components divided in `r nrow(cv)` subcategories: `r ct2(cv)`. Finally, an approach combining metrics of exposure and sensitivity -- *e.g.* stressor frequency, trophic impact, resistance, resilience, legal status -- was used to assess the [relative vulnerability](#vulnportrait) of subcategories of valued components to subcategories of environmental stressors. 

Here, we detail the general observations that arise from the cumulative effects assessment as bullet points. Additional observations are presented in the report and can also be done by exploring the results of the assessment; we invite the reader to explore section \@ref(resultats) of the report for more information, and in particular to explore the figures provided. All the data evaluated and used for this assessment are available in [appendix 1](#annexe1) and updates to the assessment are detailed in [appendix 10](#annexe10).


<br/>



- **Distribution of environmental stressors arising from marine vessel activities**
  - The whole study area is exposed to environmental stressors;
  - Major port cities and the St. Lawrence waterway are particularly exposed to cumulative stressors;
  - Shipping and maritime pollution are the most widely spread stressors in the study area.

<br/>

- **Distribution of valued components**
  - The whole study area is covered by one or several valued components;
  - Coastal areas are characterized by the greatest diversity of valued components;
  - The region of Lake Saint-Pierre is particularly rich in valued components;
  - In the maritime sector, the mouth of the Saguenay River has the greatest valued component diversity.

<br/>

- **Distribution of cumulative effects**
  - The whole study area is affected by the cumulative effects of marine vessel activities at varying levels of intensity;
  - Cumulative effects are particularly intense and concentrated in the fluvial sector; the most intense effects are located in the regions of Quebec and the south of Île d'Orléans, lake Saint-Pierre, and the St. Lawrence waterway between Trois-Rivière and Montreal;
  - Cumulative effects are more diffuse in the maritime sector; the most intense effects are located at the mouth of the Saguenay River.

<br/>

- **Most important environmental stressors**
  - Shipping and maritime pollution have the most important cumulative effects predicted at the regional scale, as they are also the most widespread in the study area;
  - Commercial fisheries affect certain valued component categories more intensively, such as many sites of interest, habitats of the fluvial sector and mollusk beds in the marine sector. Commercial fisheries in the fluvial sector seem to have a greater global effect than that of commercial fisheries in the marine sector, likely due to the smaller spatial extent of the fluvial sector compared to that of the marine sector.
  - Anchorages, accidental spills and dredging activities have localized effects on certain valued components. Those stressors, even if less widespread, combine with shipping and maritime pollution and are generally located in areas that are the most affected to cumulative effects (*e.g.* lake Saint-Pierre).

<br/>

- **Valued components most affected**
  - Sites of cultural, heritage and archeological interest are particularly exposed to the effects of marine vessel activities. Although this result is expected considering their high vulnerability in the context of this study, it remains an important observation and showcases the overlap between sites of interest for First Nations and marine vessel activities in the study area;
  - Sites of interest for First Nations in the fluvial sector are more exposed to the effects of marine vessel activities because of the high concentration of effects in the sector;
  - Bank integrity in the fluvial sector is particularly affected by shipping, especially in the lake Saint-Pierre;
  - Habitats that were considered are affected by a wide variety of environmental stressors and predicted cumulative effects also varies between habitat types;
  - Although marine mammals seem less affected than other valued components by the effects of marine vessel activities, it is important to consider the wide spatial distribution of those species in the maritime sector of the study area. Cumulative effects on marine mammals are instead localized and most intense at the mouth of the Saguenay River.

<br/>

- **Administrative regions most affected**
  - Administrative regions of the fluvial sector are the most affected by the cumulative effects of marine activities, particularly for the Montérégie and Centre-du-Québec regions. Those effects are primarily influenced by commercial shipping (*e.g.* tankers, dry bulk, cargo, and container carriers), commercial fisheries and marine pollution.
  - The Côte Nord region is the administrative region most affected in the maritime sector, mostly due to the effects of shipping on marine mammals.


