## Résultats détaillés

L’évaluation des effets cumulés offre un indice intégrateur qui peut être utilisé afin d’explorer le cumul des effets des facteurs de stress en détails. Une exploration détaillée des effets associés à chaque facteur de stress sur chaque composante valorisée sera effectuée (Figure 2 G, H). Par exemple, nous explorerons les effets cumulatifs des activités maritimes sur les habitats floristiques et fauniques séparément des effets cumulatifs sur les sites d’importances de la zone d’étude. Nous explorerons également la répartition spatiale des effets cumulés au sein des deux secteurs de la zone d’étude séparément. L’exposition cumulée (Figure 2D) sera aussi analysée afin d’identifier les milieux de la zone d’étude les plus exposés aux facteurs de stress issus des activités maritimes.

Ces diagnostics d’analyse permettront, entre autres, d’explorer l’indicateur d’effets cumulés et d’identifier les composantes valorisées les plus touchées par le cumul des effets des facteurs de stress dans la zone d’étude, les facteurs de stress les plus préoccupants ainsi que les zones les plus exposées au cumul des effets des facteurs de stress. Lors de ces étapes, nous pourrons également identifier des séquences des effets [@pechesetoceanscanada2015a] qui sont les plus susceptibles d’impacter les différentes composantes valorisées considérées par l’évaluation des effets cumulatifs. Une séquence des effets établit les liens entre les activités et leurs incidences potentielles sur divers aspects de l’écosystème.

Nous identifierons également les chemins d’exposition des composantes valorisées aux différents facteurs de stress, *c.-à-d.* les milieux où la répartition des facteurs de stress chevauche celle des composantes valorisées. Cet indice, qui ne considère pas la vulnérabilité des composantes valorisées aux facteurs de stress, permettra d’identifier les facteurs de stress auxquels les composantes valorisées sont le plus fréquemment exposées dans la zone d’étude. Considérant l’incertitude et les difficultés d’évaluation de la vulnérabilité des composantes valorisées, cet indice relatif permet d’utiliser strictement les données qui sont typiquement les plus robustes – caractérisation des facteurs de stress et des composantes valorisées – afin d’identifier les milieux et les composantes valorisées les plus à risque dans la zone d’étude


### Incertitudes et lacunes

Les résultats et les conclusions de l’évaluation seront limités par la disponibilité des données. Il est donc important de convenablement documenter l’incertitude associée à chaque sources de données ainsi que toutes lacunes en connaissances identifiées pendant le processus d’évaluation des effets cumulatifs. Cet aspect est particulièrement important puisqu’il s’agit d’une étude pilote qui ne pourra répondre à l’ensemble des questionnements reliés aux effets cumulés des activités maritimes dans le Saint-Laurent.


### Considérations particulières

- L’évaluation relative des effets cumulatifs proposée est explicitement spatiale: elle fournira une description de la répartition spatiale et de l’intensité relative des effets cumulés dans la zone d’étude. Ce type d’approche régionale impose quelques contraintes, notamment la nécessité d’utiliser principalement des facteurs de stress et des composantes valorisées dont une caractérisation spatiale est possible, idéalement pour l’ensemble de la zone d’étude; ceci rend l’utilisation d’études ponctuelles difficile. Par exemple, il serait difficile d’inclure une évaluation d’impacts de la pêche sur une population d’anguille à l’embouchure d’une seule rivière de la zone d’étude.

- Dans le cadre de cette étude pilote, nous nous concentrerons sur une évaluation contemporaine des effets cumulatifs, c.-à-d. au cours des 5 à 10 dernières années selon les données disponibles; les données historiques permettant l’identification d’états de référence ne seront ainsi pas utilisées, à moins qu’un besoin particulier soit identifié. Bien que pertinent, le contexte de l’étude et la disponibilité des données ne nous permettra pas d’évaluer un état de référence pour l’ensemble des facteurs de stress et des composantes valorisées caractérisés, limitant ainsi les conclusions temporelles que nous pourrions en tirer.

- La disponibilité des données guidera le travail que nous pouvons accomplir pour ce projet pilote. Le contexte de l’étude ne permet pas à l’équipe de l’Université Laval d’effectuer une collecte de données nouvelles. Le portrait établi représentera ainsi une veille des connaissances actuelles permettant de caractériser les facteurs de stress des activités maritimes ainsi que les composantes valorisées identifiées. Advenant la disponibilité de nouvelles données en cours de projet, l’équipe de l’Université Laval pourra les considérer, à condition que leur inclusion ne les force pas à repousser le dépôt des livrables du contrat.

- Finalement, plusieurs autres activités humaines peuvent être à la source de pressions environnementales au sein de la zone d’étude. Par exemple, la qualité de l’eau est assurément influencée par les activités en milieu terrestre et le lessivage des terres agricoles par les embouchures de rivières. Par contre, la présente étude ne se concentrera que sur les facteurs de stress issus des activités maritimes.
