# Limites de l'évaluation {#limiteeval}

```{r pathwayssetup2, echo = FALSE}
st <- read.csv("../data/data-metadata/metadata_stresseurs.csv")
cv <- read.csv("../data/data-metadata/metadata_composantes_valorisees.csv")
```

Cette section présente certaines des limites relatives à la méthode utilisée, aux éléments du portrait de la zone d'étude et aux résultats de l'évaluation. Des limites relatives à la portée de l'étude sont également présentées à la section \@ref(limiteportee) du rapport, bien que certaines soient réitérées plus bas dans le contexte du portrait et de l'évaluation des effets cumulatifs effectuée.  

- La limite la plus importante de l'étude est l'utilisation d'un indice relatif des effets des stresseurs environnementaux sur les composantes valorisées. Bien qu'une telle approche offre des avantages clairs comme la possibilité d'inclure divers sources de données et d'adopter une approche holistique pour l'évaluation des effets cumulatifs, elle ne permet pas de mettre en évidence un effet absolu des stresseurs environnementaux sur les composantes valorisées, *i.e.* une variation de l'état d'une composante valorisée face aux effets cumulatifs des activités maritimes. Les résultats doivent ainsi être interprétés comme une probabilité de risque des activités maritimes sur les composantes valorisées considérées.

- La portée de l'étude constitue la deuxième limite la plus importante de l'évaluation : *l'évaluation est entièrement contrainte par les stresseurs environnementaux et par les composantes valorisées considérés. Aucune interprétation débordant cette portée ne peut être effectuée*.

-  Premièrement, il s'agit d'une évaluation sectorielle des effets cumulatifs concentrée sur les activités maritimes liées à la navigation. Pour une évaluation régionale des effets cumulatifs plus intégrative, il serait nécessaire de considérer l'ensemble des stresseurs environnementaux affectant la zone d'étude. En plus des activités maritimes, la zone d'étude est soumise à une variété de stresseurs environnementaux tels les changements climatiques et les stresseurs d'origine terrestre [*e.g.* @beauchesne2020]. L'ajout de ces autres stresseurs pourrait permettre de convrir la composante valorisée visant la qualité de l'eau, qui demeure une préoccupation justifiée des communautés locales; l'[évaluation régionale de la région du fleuve Saint-Laurent](https://iaac-aeic.gc.ca/050/evaluations/document/140637?culture=fr-CA) récemment autorisée par le ministre de l’Environnement et du Changement climatique du Canada suite à une [demande présentée par la Nation Mohawk de Kahnawà:ke](https://iaac-aeic.gc.ca/050/documents/p80913/135682E.pdf) pourrait également permettre de couvrir  d'autres sources de stress importantes. Nous croyons que l'évaluation effectuée dans le cadre de ce projet pilote pourra supporter et informer cette évaluation régionale. Nous croyons toutefois qu'elle ne peut être considérée comme une évaluation exhaustive des effets cumulatifs  permettant d'adresser l'ensemble des préoccupations énoncées par les communautés locales.

- Deuxièmement, les composantes valorisées sélectionnées représentent une série de préoccupations identifiées par des experts et des communautés locales et diverses parties prenantes lors d'activités de concertation et de co-développements à l'origine de ce projet pilote. Ces préoccupations sont valides et importantes, mais elles ne peuvent être considérées représentatives de l'entièreté des composantes environnementales, sociales, culturelles, patrimoniales et archéologiques d'importance au sein de la zone d'étude. Il est donc important d'interpréter les résultats de l'évaluation uniquement dans le contexte des composantes valorisées identifiées. Par exemple, une intensité inférieure des activités maritimes sur les composantes valorisées au sein du secteur maritime ne signifie pas l'absence d'effets environnementaux ou sociaux. Ces résultats seraient différents si des composantes valorisées différentes étaient considérées. Par exemple, si l'évaluation n'avait considéré que les mammifères marins, les effets cumulatifs n'auraient été prédits que dans le secteur maritime. Cette approche n'aurait en rien signifié que les activités maritimes n'exercent aucune pression environnementale ou sociale au sein du secteur fluvial.

- Une troisième limite de l'évaluation est la disponibilité et l'accessibilité aux données. Puisqu'aucune nouvelle donnée n'était collectée dans le cadre de ce projet, le portrait présenté représente une veille des connaissances de données disponibles et accessibles pour décrire les stresseurs et les composantes valorisées considérées. Dans certains cas, des données étaient indisponibles (*e.g.* rejets opérationnels de la flotte internationale), alors que dans certains cas elles étaient inaccessibles même si elles existent (*e.g.* pêche commerciale dans le secteur fluvial et bruit maritime). Certaines données sont également en cours d'acquisition à travers d'autres projets de caractérisation du milieu, comme une caractérisation des herbiers aquatiques. Ces données, lorsque disponibles, pourront aisément être ajoutées à l'évaluation des effets cumulatifs. La section suivante sur les perspectives discute de quelques exemples spécifiques de données qui pourraient être ajoutées à l'évaluation afin d'en bonifier la portée.

- L'évaluation proposée est régionale et explicitement spatiale; elle nécessitait ainsi des données spatialisées à une échelle régionale ou qui pouvaient être rattachées à des éléments de la zone d'étude afin d'être incluses à l'évaluation. L'utilisation de données ponctuelles ne couvrant qu'une portion du territoire était ainsi difficile, tout comme l'ajout de considérations d'ordre sociales et culturelles comme l'attachement territorial. Ces considérations demeurent toutefois importantes et ont été considérées dans le cadre d'une autre étude parallèle effectuée par l'équipe de Roxane Lavoie de l'Université Laval.

- L'évaluation a été effectuée au sein d'une grille d'étude de 1 $km^2$ couvrant une zone d'étude de près de 15 000 $km^2$, en considérant `r nrow(st)` catégories de stresseurs et `r nrow(cv)` catégories de composantes valorisées. L'interprétation des résultats doit être faite en considérant la résolution, l'étendue, et la quantité d'éléments inclus à l'évaluation; toute interprétation qui déborde de ces paramètres est nécessairement erronnée. 

- Dans le cadre de cette étude pilote, nous nous sommes concentrés sur une évaluation contemporaine des effets cumulatifs, *i.e.* en concentrant notre recherche de données sur la période couvrant les 5 à 10 dernières années. Bien que nous ayons pu obtenir une caractérisation allant au-delà ce cette période pour plusieurs catégories de stresseurs et de composantes valorisées, les résultats ne représentent pas une évaluation historique des effets cumulatifs. Aucun état de référence n'a ainsi été établi afin de comparer l'état d'un milieu à lui-même à travers le temps. Les comparaisons pouvant être faites sont ainsi davantage spatiales que temporelles.

- L'exposition des composantes valorisées aux stresseurs environnementaux peut afficher des variations intra-annuelles ou saisonnières. Par exemple, l'intensité de la navigation est moindre en hiver qu'en été; les effets d'un déversement accidentel ne seront pas les mêmes lorsqu'il y a un couvert de glace. Dans le cas d'un décalage temporel complet entre une composante valorisée et un stresseur, il est possible d'utiliser l'évaluation de la vulnérabilité pour pallier à cette lacune; c'est ce que nous avons fait pour la vulnérabilité du phoque du Groenland aux activités d'observation de mammifères marins (voir section \@ref(vulnmm)). La vulnérabilité à elle seule n'est cependant pas suffisante pour considérer une dynamique temporelle plus complexe. L'évaluation des effets cumulatifs proposée assume ainsi globalement une dynamique annuelle constante. L'étude de la dynamique temporelle des effets cumulatifs est cependant un sujet peu mentionné dans la littérature sur l'évaluation des effets cumulatifs similaires à celle effectuée dans le cadre du présent projet. Il serait ainsi pertinent d'approfondir ces évaluations afin de considérer l'exposition temporelle en plus de l'exposition spatiale.
