## Mammifères marins


Liste des espèces pour lesquelles nous auront des informations:

1. Beluga
2. North Atlantic right whale
3. Northern Bottlenose whale
4. Blue whale
5. Fin whale
6. Sei whale
7. Minke whale
8. Humpback whale
9. Sperm whale

Pour plus de
WhaleSightings.XMAR@dfo-mpo.gc.ca

Si on souhaite obtenir plus de données rapidement sur d’autres espèces, faire une nouvelle demande des données XMAR auprès de Pam Emery au MPO (WhaleSightings.XMAR@dfo-mpo.gc.ca).


Hi Aurelie,

Sorry this took a little bit, I had to go back to Meg’s original report to refresh myself on the methods. I’ve put my answers below which should cover David’s questions 😊

#1.  When I look at the rasters, I am not able to get the same maps as in the guide and would like to make sure I understand the data correctly. Reading the report, I see that you have done Gaussian smoothing on the data. I imagine that these are the rasters with the following names p_BELUGA_gauss_w.tif? Then you did a logarithmic transformation and I imagine that these are the files with the name: Log_p_BELUGA_gauss_w.tif. CORRECT?

That is correct, you can see my reply to #3 for a breakdown of the processing steps.

#2. For data without logarithmic transformation, the raster values ​​are in what unit?

The units for the non-log transformed data can be thought of as the proportion (%) of the total number of observances of that species that fell within each cell (observances in cell/total observances is study area) . i.e. if there was 100 beluga sittings within the study area, and 10 of them were within a specific cell, that cell would have a value of 0.1. The only small caveat here is that the a data was smoothed with a 0.2o gaussian filter before being normalized in this way.

#3. I imagine this you used the data from the rasters with a log transformation? If so, I am not sure I understand the operation of standardization so that the sum in the whole domain is equal to 1. What constitutes the domain? The study area? If so, when I sum the cells on my side it doesn't add up to 1, so I feel like something is missing.

Correct we did use the log transformed data for the guide maps. The log transformation was done to make hotspots stand out more, and was done after the operation of standardizing the data. This means the log transformed rasters would not be expected to sum to 1. The order of operations was as follows:



    Split study domain (40 o to 55 o N x -72 o to -48 o W) into 0.05 o gridcells
    The number of individual whales sighted in each gridcell was summed
    A 0.2 o  gaussian smoother was applied
    Values in each cell were relativized by the total number of observances so that the sum of the entire domain equaled 1
        This is what is displayed in the rasters with the ex.“p_BELUGA_gauss_w.tif” naming convention
    These standardized rasters where then log10 transformed
        This is what is displayed in the rasters with the ex.“Log_p_BELUGA_gauss_w.tif” naming convention

 
