## Vulnérabilité {#vulnerabilite}

L’évaluation des effets cumulatifs nécessite une évaluation de la vulnérabilité des composantes valorisées aux stresseurs environnementaux considérés [@teck2010; @kappel2012]. D’ordre général, la vulnérabilité d’une composante valorisée est définie en fonction de son exposition (c.-à-d. la probabilité qu’un habitat sera soumis à un stresseur), de sa sensibilité  (c.-à-d. le degré auquel un habitat sera affecté par un stresseur) et de sa capacité d’adaptation ou de sa résilience (c.-à-d. la capacité d’un habitat ou des éléments le composant à se rétablir suite à une perturbation) aux sources de stress [e.g. @metzger2005; @teck2010; @halpern2013].

Plusieurs méthodes sont décrites dans la littérature scientifique afin d’évaluer la vulnérabilité d’attributs naturels à des perturbations naturelles ou anthropiques [@wilson2005]. Par exemple, @foden2011 ont utilisé des valeurs empiriques de temps de rétablissement provenant de la littérature comme marqueur de vulnérabilité des habitats benthiques au Royaume-Uni afin d’appliquer la méthode de @halpern2008. Des lacunes majeures au niveau des données empiriques disponibles permettant de caractériser l’ensemble des combinaisons composantes valorisées-stresseurs sont toutefois notables et entravent l’utilisation d’une telle approche [@halpern2007; @teck2010]. Ce type de connaissance peut être particulièrement difficile à obtenir et des équipes de recherche entières s’intéressent typiquement à la vulnérabilité d’une seule composante valorisée à une seule source de stress; pensons à la vulnérabilité des mammifères marins au bruit sous-marin. De plus, bien que la vulnérabilité de certaines composantes valorisées à certains facteurs de stress soit bien documentée et permettrait une évaluation robuste des impacts environnementaux individuels, ce type de connaissance est rarement – voire jamais – disponible pour l’ensemble des combinaisons "composantes valorisées-stresseurs"; c’est pourtant une nécessité pour effectuer une évaluation d’effets cumulatifs.

Une approche qualitative faisant appel à l’opinion d’experts et/ou à la recherche bibliographique est ainsi généralement utilisée afin de générer une matrice de scores de vulnérabilité relative pour tous les écosystèmes et les stresseurs inclus à l’évaluation d’impacts cumulés [@halpern2007; @teck2010; @kappel2012]. L’utilisation d’une méthode par consultation d’experts permet également de valoriser les expertises et les connaissances qui ne seraient autrement pas disponibles pour appuyer la gestion et la prise de décision [@wilson2005; @teck2010]. Des critères visant à évaluer l'exposition, la sensibilité et les capacités adaptatives des composantes valorisées sont ainsi généralement sélectionnés et évalués qualitativement. Par exemple, l’exposition peut dépendre de l’étendue spatiale et de la fréquence d’une source de stress; la sensibilité d’une espèce peut être définie par les effets d’une source de stress sur sa reproduction; les capacités adaptatives peuvent être influencées par le statut vulnérable d’une certaine population animale. Ces critères peuvent varier selon les composantes valorisées sélectionnées puisque des critères applicables à une espèce [e.g. @maxwell2013] ne le seront pas nécessairement à un habitat [e.g. @teck2010]. Les critères peuvent ainsi varier d’un groupe de composantes valorisées à l’autre; c'est d'ailleurs le cas pour les différentes composantes valorisées considérées pour l'évaluation de ce projet pilote.

Une évaluation qualitative de la vulnérabilité vise à évaluer chaque critère sélectionné afin d’obtenir une évaluation numérique par critère. Ces évaluations individuelles sont ensuite combinées et normalisées afin d’obtenir un score de vulnérabilité relative variant entre 0 -- insensible -- et 1 -- très sensible -- pour l’ensemble des combinaisons "composantes valorisées-stresseurs". Les prochaines sections décrivent comment la vulnérabilité des composantes valorisées aux sources de stress a été évaluée dans le cadre de la présente évaluation.
