### Sites d’intérêt culturels, patrimoniaux et archéologiques

Les sites d'intérêt sont principalement constitués de sites identifiés par les Premières Nations. Ces sites représentent l'utilisation et l'occupation du territoires par les différentes Nations participantes et ont déjà été jugées importantes pour le projet. Déterminer la vulnérabilité relative d'un site d'intérêt pour une communauté telle qu'effectué pour les autres composantes valorisées (voir sections précédentes) serait un exercice similaire à attribuer une valeur supérieure ou inférieure aux sites entre eux. Or, attribuer une valeur à un site d'intérêt est un exercice particulièrement complexe, voire impossible. Par exemple, un site de chasse a-t-il plus de valeur qu'un site archéologique? Comme noté par le Grand Conseil de la Nation Waban-Aki [@gcnwa2021] :

> [...] il est impossible de cartographier adéquatement les valeurs accordées à certains sites ou activités. L’importance d’un site dépend d’une multitude de facteurs. Par exemple, sans être fréquentés sur une base régulière, des lieux sont associés à des récits ou légendes, à l’histoire ou l’imaginaire collectif de la Nation, à des sites archéologiques ou sacrés, etc.

À cet égard, et après discussions avec plusieurs représentants des communautés, nous avons jugé qu'il serait inadéquat d'attribuer un score de vulnérabilité aux sites identifiés dans le cadre de ce projet pilote. Nous avons plutôt attribué une valeur de vulnérabilité égale à 1 pour l'ensemble des sites d'intérêt identifiés. Ceci ne veut pas dire que tous les sites sont automatiquement considérés comme affectés par les activités maritimes pour l'évaluation des effets cumulatifs. L'évaluation des effets cumulatifs devient plutôt le résultat du croisement entre la distribution et l'intensité des stresseurs environnementaux et la distribution des sites d'intérêt, *i.e.* l'exposition des sites d'intérêt aux stresseurs environnementaux. Un site d'intérêt exposés à plusieurs stresseurs à haute intensité serait ainsi plus affectué qu'un site d'intérêt qui n'est pas exposé aux stresseurs environnementaux considérés. 

L'utilisation d'une valeur de vulnérabilité égale à 1 pour l'ensemble des sites d'intérêt a toutefois un effet sur l'évaluation globale des effets cumulatifs incluant l'ensemble des composantes valorisées; en effet, les sites d'intérêt reçoivent un score de vulnérabilité maximal, ce qui n'est pas le cas pour les autres composantes valorisées considérées au sein de cette évaluation (voir sections précédentes). En termes relatifs, la vulnérabilité des sites d'intérêt est ainsi considérée supérieure à la majorité des autres composantes valorisées incluses à l'évaluation. Ceci impose nécessairement un biais "en faveur" des sites d'intérêt pour l'évaluation globale. Les résultats de l'évaluation sont toutefois présentés et discutés par composantes valorisées individuelles afin de palier à ce biais.

Afin d'assurer une continuité pour la vulnérabilité des sites d'intérêt, une valeur de vulnérabilité égale à 1 a également été attribuée aux sites d’intérêt publics, *i.e.* les aires protégées et les sites patrimoniaux.
