## Résultats

### Transformation et normalisation des stresseurs environnementaux

Une transformation logarithmique a été appliquée aux données de stresseurs environnementaux afin d'éviter une sous-estimation de l'intensité des stresseurs à valeurs intermédiaires [@halpern2019]. Tous les stresseurs ont également été normalisés entre 0 et 1 pour obtenir une valeur relative d'intensité et ainsi permettre une comparaison entre différents types de stresseurs. Le 99e quantile de la distribution d'intensité des stresseurs a été utilisé comme limite supérieure pour la normalisation des valeurs extrêmes [@halpern2019]. Les catégories de navigation ont été normalisées conjointement afin d'éviter d'attribuer des valeurs d'intensité relative supérieures à des types de navires pour lesquels le traffic est inférieur. Par exemple, une normalisation individuelle résulterait en une intensité maximale similaire pour une catégorie de navigation dont le traffic maximal est de 100 navires par $km^2$ et une autre dont le traffic maximal est de 1000 navires par $km^2$. Une normalisation jointe permet ainsi de conserver ces différentes entre types de navires. Les autres stresseurs ont été normalisés individuellement.
