# Perspectives et prochaines étapes

## Description des habitats fauniques et floristiques

La caractérisation des habitats utilisés pour l'évaluation des effets cumulatifs présentée dans ce projet pilote présente en réalité deux types d'habitats, soit des habitats pouvant être perçus comme des écosystèmes uniques, et des habitats représentant des milieux d'importance pour des espèces. Les milieux d'importance pour les espèces ne représentent pas un écosystème, mais plutôt des lieux connus pour leur importance pour certaines espèces ou groupes d'espèces. Ces sites se retrouvent évidemment au sein d'habitats tels des milieux humides et des herbiers aquatiques. En tant que tel, l'identification de ces sites uniques, précaires ou vulnérables pourraient être utilisés afin de moduler l'évaluation de la vulnérabilité des différents habitats selon leur importance pour des espèces. Ainsi, un milieu humide abritant des espèces en péril pourrait voir sa vulnérabilité aux effets des sources de stress augmenter comparativement à un milieu humide qui n'abrite aucune espèce en péril connue. Une description exhaustive des habitats n'a toutefois pu être obtenue pour l'entièreté la zone d'étude. Par conséquent, les habitats d'importance pour les espèces ont été retenus en tant qu'habitats distincts plutôt que comme critère permettant de moduler la vulnérabilité des habitats. Une mise à jour de l'évaluation des effets cumulatifs pourrait avoir pour objectif une caractérisation exhaustive des habitats et l'ajout de critères visant à évaluer leur vulnérabilité permettant de considérer les sites connus pour leur importance écologique.

## Pêches commerciales dans le Saint-Laurent fluvial


## Effets indirects


## Vulnérabilité des habitats


## Équivalences vulnérabilité des composantes valorisées
