### Water quality

Water quality was identified as a valued component in the various engagement workshops for identifying valued components. However, water quality is affected by a suite of multiple factors including agriculture, air pollution, and sewage discharge [@sasakova2018]. In the fluvial sector, water quality appears to be affected primarily by land use; proximity to a large city or agriculture directly impact water quality [@vigil2003]. Water quality is also greatly affected by the large amount of farmland draining into Lake St. Pierre[@hudon2008; @goyette2016]. Marine activities are generally not cited as a significant potential source of pollution affecting water quality [@butts1992].

While water quality remains a valid concern, it is difficult to link water quality measures specifically to marine activities. As such, we consider that a characterization of water quality as part of a sectoral cumulative effects assessment focused on marine activities would likely risk inappropriately assigning responsibility to a sector of activity. To address this issue, we decided instead to adopt an alternative approach to consider the risks to water quality associated with marine activities. The authors of the study @halpern2019 considered water quality as a marine pollution stressor instead. This stressor was described by combining the various individual stressors related to marine activities, i.e. shipping and port activities in their case. We have thus opted for a similar approach and consider marine pollution as an environmental stressor, replacing the water quality valued component. Please refer to the section on environmental stressors for a description of the marine pollution stressor.

<br/>
