### Areas of cultural, heritage and archeological interest

The areas of interest are mainly sites identified by the First Nations. These areas of interest represent the use and occupation of the territory by the various participating Nations and have already been deemed important to the project on the basis that marine vessel activities may affect the conditions that underlie the exercise of First Nations’ Indigenous rights. Determining the relative vulnerability of an area of interest to an Indigenous Nation as done for the other valued components (see previous sections) would be akin to assigning a higher or lower value to sites by comparing them to each other. However, assigning a value to an area of interest is a particularly complex, if not impossible, exercise. For example, is a hunting site more valuable than an archeological site? As noted by the Grand Council of the Waban-Aki Nation [@gcnwa2021]:


> [...] it is impossible to appropriately map the values assigned to particular sites or activities. The importance of a site depends on a multitude of factors. For example, although not visited on a regular basis, some places are associated with stories or legends, with the history or collective imagination of the Nation, with archeological or sacred sites, etc.

In this regard, and after discussions with a number of representatives of the participating First Nations, we deemed that it would be inappropriate to assign a vulnerability score to the sites identified in the context of this pilot project. Instead, we have assigned a vulnerability value of 1 for all the identified areas of interest. This does not mean that all areas of interest are automatically considered affected by marine vessel activities for the cumulative effects assessment. Rather, the cumulative effects assessment becomes the result of intersecting the distribution and intensity of environmental stressors with the distribution of areas of interest, *i.e.* the exposure of areas of interest to environmental stressors. This means that an area of interest exposed to several high-intensity stressors would be more affected than an area of interest that is not similarly exposed to the environmental stressors considered. 

Using a vulnerability value of 1 for all areas of interest has an effect, however, on the overall assessment of cumulative effects including all valued components; areas of interest receive a maximum vulnerability score, which is not the case for the other valued components considered in this assessment (see previous sections). In relative terms, the vulnerability of the areas of interest is thus considered higher than most of the other valued components included in the assessment. This necessarily imposes a bias “in favour” of the areas of interest for the overall assessment. However, the results of the assessment are presented and discussed by individual valued components to overcome this bias.

To ensure continuity for the vulnerability of areas of interest, a vulnerability value of 1 was also assigned to areas of public interest, *i.e.* protected areas and heritage sites.
