# Limits and perspectives {#perspective}

Ce projet pilote visait à fournir une première évaluation des effets cumulatifs des activités maritimes au sein de la zone d'étude. En tant que tel, il est attendu que cette évaluation constitue une première étape de l'établissement d'un processus d'évaluation durable et cyclique. Cette section présente ainsi certaines des limites et perspectives relatives à la méthode utilisée, aux éléments du portrait de la zone d'étude et aux résultats de l'évaluation. Des limites relatives à la portée de l'étude sont également présentées à la section \@ref(limiteportee) du rapport, bien que certaines soient réitérées au sein de cette section.  


## Sites d'intérêt culturels, patrimoniaux et archéologiques {.unlisted .unnumbered #projetroxane}

La caractérisation des sites d'intérêt culturels, patrimoniaux et archéologiques des Premières Nations est accompagnée d'une série de limites et considérations à l'interprétation des résultats qui devrait être consultée par tout lecteur qui désire convenablement interpréter les résultats de l'évaluation des effets cumulatifs relatifs aux sites d'intérêt. Ces limites sont présentées à la section \@ref(pnportrait) du rapport. L'intégration de dimensions d'ordre sociales et culturelles représente néanmoins une lacune majeure pour l'évaluation des effets cumulatifs en général. Il n'a pu être possible, par exemple, d'attribuer des valeurs de vulnérabilité aux sites d'intérêt identifiés par les Premières Nations participantes; bien que difficile, certains représentants des Premières Nations nous ont indiqué qu'une évaluation de la vulnérabilité des sites pourrait permettre d'identifier certains sites plus à risque que d'autres aux activités maritimes. Ce travail débordait à la fois de notre mandat et de notre expertise; les résultats présentés se limitent ainsi essentiellement à l'évaluation de l'exposition cumulée des sites d'intérêt aux stresseurs environnementaux issus des activités maritimes. 

Face à ce constat, une étude connexe a été enclenchée avec l'équipe de Roxane Lavoie, professeure à l’École supérieure d’aménagement du territoire et de développement régional de l’Université Laval, afin de s'intéresser spécifiquement aux dimensions socioculturelles de l'évaluation des effets cumulatifs. Le projet, intitulé *Cultures et Nations Saint-Laurent*, a pour but de comprendre comment les communautés autochtones ont vécu l’intensification des activités maritimes sur le fleuve et de quelle façon leur attachement au territoire en a été affecté. Ce projet se déroule en étroite collaboration avec des représentant.e.s des Nations W8ban-Aki, Huronne-Wendat, Innue, Kanien'kehá:ka (Mohawk) et Wolastoqiyik. Il est financé par Transports Canada et le Réseau Québec maritime (RQM). 

***Perspective*** : les résultats de l'évaluation des effets cumulatifs présentés au sein de ce rapport pourraient être utilisés pour informer le projet *Cultures et Nations Saint-Laurent*. Similairement, le projet *Cultures et Nations Saint-Laurent* pourrait apporter des pistes d'interprétation des résultats de la présente étude afin d'explorer davantage les conséquences potentielles des effets cumulatifs des activités maritimes au sein de milieux d'importance pour les Premières Nations qui sont particulièrement à risque. 


## Évaluation régionale {.unlisted .unnumbered}

Tel que mentionné en introduction du rapport, une limite imposée à la présente évaluation est sa portée sectorielle concentrée sur les activités maritimes liées à la navigation; elle ne peut ainsi être considérée comme une évaluation exhaustive des effets cumulatifs permettant d'adresser l'ensemble des préoccupations énoncées par les communautés locales. Pour une évaluation régionale des effets cumulatifs plus intégrative, il serait nécessaire de considérer l'ensemble des stresseurs environnementaux affectant la zone d'étude comme les changements climatiques et les stresseurs d'origine terrestre [*e.g.* @beauchesne2020]. L'ajout de ces autres stresseurs pourrait permettre de couvrir la composante valorisée visant la qualité de l'eau, qui demeure une préoccupation justifiée des communautés locales.

***Perspective*** : l'[évaluation régionale de la région du fleuve Saint-Laurent](https://iaac-aeic.gc.ca/050/evaluations/document/140637?culture=fr-CA) récemment autorisée par le ministre de l’Environnement et du Changement climatique du Canada suite à une [demande présentée par la Nation Mohawk de Kahnawà:ke](https://iaac-aeic.gc.ca/050/documents/p80913/135682E.pdf) pourrait également permettre de couvrir d'autres sources de stress importantes. Nous croyons que l'évaluation effectuée dans le cadre de ce projet pilote devrait supporter et informer cette évaluation régionale. 

## Rivière Saguenay {.unlisted .unnumbered}

La Rivière Saguenay n'est pas un milieu identifié à risque des effets cumulatifs de la navigation au terme de notre évaluation des effets cumulatifs. Ce résultat doit cependant être contextualisé. En effet, une manque de connaissance généralisé caractérise cette région de la zone d'étude, de telle sorte qu'il est n'est pas possible, à la lumière de notre évaluation, de déteminer les risques réels posés par les activités maritimes au sein de cette région. 

***Perspective*** : prioriser une caractérisation écologique, sociale et culturelle de la Rivière Saguenay et refaire une évaluation des effets cumulatifs.

## Caractérisation des habitats {.unlisted .unnumbered}

La caractérisation des habitats utilisés pour l'évaluation des effets cumulatifs présentée dans ce projet pilote présente deux types d'habitats : 1) des habitats représentant des écosystèmes uniques et 2) des habitats représentant des milieux d'importance pour des espèces. Les milieux d'importance pour les espèces ne représentent pas un écosystème, mais plutôt des lieux connus pour leur importance pour certaines espèces ou groupes d'espèces. Ces sites se retrouvent évidemment au sein d'habitats tels des milieux humides et des herbiers aquatiques. En tant que tel, l'identification de ces sites uniques, précaires ou vulnérables pourraient être utilisée afin d'attribuer une vulnérabilité supérieure aux différents types d'habitats dans lesquels ils se retrouvent. Ainsi, un milieu humide abritant des espèces en péril pourrait voir sa vulnérabilité aux effets des sources de stress augmenter comparativement à un milieu humide qui n'abrite aucune espèce en péril connue. Une description exhaustive des habitats n'a toutefois pu être obtenue pour l'entièreté la zone d'étude. Par conséquent, les habitats d'importance pour les espèces ont été retenus en tant qu'habitats distincts plutôt que comme critère permettant de moduler la vulnérabilité des habitats. 

***Perspective*** : réaliser une caractérisation exhaustive des habitats et définir/ajouter des critères pour évaluer leur vulnérabilité et refaire une évaluation des effets cumulatifs.


## Vulnérabilité des habitats {.unlisted .unnumbered}

L'évaluation de la vulnérabilité des habitats a été effectuée à partir d'études antérieures ayant fait appel à des 107 experts afin d'évaluer des scores de vulnérabilité de 19 types d'habitats à 53 stresseurs environnementaux [@teck2010; @kappel2012] et ces travaux ont déjà été repris, révisés et adaptés à de mainte reprises depuis [*e.g.* @maxwell2013; @clarkemurray2015; @clarkemurray2015a; @trew2019]. Cependant, aucune de ces études est spécifique à notre zone d'étude ou effectuée au sein de milieux d'eau douce.

***Perspective*** : effectuer une révision des scores utilisés pour évaluer la vulnérabilité des habitats aux stresseurs environnementaux avec des experts de la zone d'étude et refaire une évaluation des effets cumulatifs. Par exemple, il serait pertinent de valider si la vulnérabilité utilisée pour la navigation gouvernementale et de recherche est adéquate dans le contexte de notre zone d’étude comparativement à l’étude originale de @kappel2012



## Variations intra-annuelles et saisonnières {.unlisted .unnumbered}

L'exposition des composantes valorisées aux stresseurs environnementaux peut afficher des variations intra-annuelles ou saisonnières. Par exemple, l'intensité de la navigation est moindre en hiver qu'en été; les effets d'un déversement accidentel ne seront pas les mêmes lorsqu'il y a un couvert de glace. Dans le cas d'un décalage temporel complet entre une composante valorisée et un stresseur, il est possible d'utiliser l'évaluation de la vulnérabilité pour pallier à cette lacune; c'est ce que nous avons fait pour la vulnérabilité du phoque du Groenland aux activités d'observation de mammifères marins (voir section \@ref(vulnmm)). La vulnérabilité à elle seule n'est cependant pas suffisante pour considérer une dynamique temporelle plus complexe. L'évaluation des effets cumulatifs proposée assume ainsi globalement une dynamique annuelle constante. L'étude de la dynamique temporelle des effets cumulatifs est cependant un sujet peu mentionné dans la littérature sur l'évaluation des effets cumulatifs similaires à celle effectuée dans le cadre du présent projet. Il serait ainsi pertinent d'approfondir ces évaluations afin de considérer l'exposition temporelle en plus de l'exposition spatiale.

***Perspective*** : caractériser la dynamique saisonnière et développer une approche permettant de considérer les variations en exposition temporelle des composantes valorisées aux stresseurs environnementaux au sein de l'évaluation des effets cumulatifs. Par exemple, les analyses pourraient être séparées en saisons et des résultats d'évaluation des effets cumulatifs pourraient être présentés par saison. 

## Résolution de la grille d'étude {.unlisted .unnumbered}

L'évaluation des effets cumulatifs a été effectuée grâce à l'intégration des catégories de stresseurs environnementaux et de composantes valorisées au sein d'une grille de 1 $km^2$. Il s'agit d'une résolution spatiale fine pour une évaluation régionale couvrant un territoire aussi vaste. La zone d'étude est toutefois composée de deux secteurs bien distincts, soit le secteur fluvial et le secteur maritime. Le secteur maritime est vaste spatialement; le secteur fluvial, par contre, est sinueux et beaucoup plus étroit. Par conséquent, les effets cumulatifs des activités maritimes y sont beaucoup plus concentrés que dans le secteur maritime. 

***Perspective*** : diviser le secteur fluvial par une grille à une résolution plus fine que 1 $km^2$, refaire l'intégration des catégories de stresseurs environnementaux et de composantes valorisées, et refaire une évaluation des effets cumulatifs.


## Bonifier le portrait {.unlisted .unnumbered #donneesperspective}

L'accès et la disponibilité des données constitue une limite de l'étude déjà citée; les données sont également une perspective majeure puisque de nouvelles données peuvent être intégrées à la méthode d'évaluation des effets cumulatifs proposée. Certaines perspectives relatives à la caractérisation des stresseurs environnementaux et des composantes valorisées sont parfois discutées au sein du [portrait de la zone d'étude](#portrait). En cours de projet, certaines données pertinentes n'ont toutefois pu être intégrées pour une variété de raisons. Nous présentons ici quelques exemples de données qui devraient, à notre avis, être incluses à une seconde phase de ce projet pilote. Cette liste ne devrait toutefois pas être considérée comme exhaustive puisque l'ensemble du portrait pourrait être bonifié.


<br>

***Projet résilience côtière***

Un exercice de caractérisation des berges du secteur maritime similaire à celui utilisé pour le secteur fluvial [@bernier2020; @bernier2021] a récemment été complété par l'équipe de Pascal Bernatchez à l’Université du Québec à Rimouski. Ce projet de grande envergure, intitulé [Projet Résilience Côtière](https://ldgizc.uqar.ca/Web/projets/projet-resilience-cotiere), présente une caractérisation de l'intégrité des berges, une caractérisation des habitats côtiers et de différents types d'écosystèmes côtiers, et des sites d'importance pour les usages côtiers tels les activités récréatives, des sites à haute valeur socioculturelle, des sites d'intérêt écologique et des sites patrimoniaux reconnus. Lorsque rendues disponibles, ces données pourraient être utilisées afin de bonifier la caractérisation de l'intégrité des berges, des habitats et des sites d'intérêts culturels, patrimoniaux et archéologiques.

<br>

***Bruit maritime***

Le bruit maritime est reconnu comme un stresseur issu de la navigation à considérer pour convenablement évaluer les effets des activités maritimes sur les mammifères marins. Une caractérisation du bruit maritime est disponible à travers l'[Atlas du paysage sonore marin](https://soundscape-atlas.uqar.ca/). Ces données sont toutefois inaccessibles à travers l'outil interactif et nous n'avons pu obtenir ces données pour l'évaluation. Si ces données sont rendues accessibles, elles devraient être incluses à une mise à jour de l'évaluation des effets cumulatifs des activités maritimes.


<br>

***Herbiers aquatiques***

Les herbiers aquatiques sont des milieux importants pour plusieurs espèces et le Ministère des Forêts, de la Faune et des Parcs (MFFP) et le Ministère de l'environnement et de la Lutte contre les changements climatiques (MELCC), dans le cadre des projets d'acquisition des connaissances pour le Centre d'expertise en gestion des risques d'incidents maritimes (CEGRIM), travaillent sur une mise à jour de la caractérisation des herbiers aquatiques dans divers secteurs de la zone d'étude. Lorsque complétée, cette mise à jour pourrait être intégrée à la caractérisation des habitats.


<br>

***Pêches commerciales dans le secteur fluvial***

Une pêche commerciale est effectuée au sein du secteur fluvial de la zone d’étude. Les données disponibles n’ont toutefois pu être obtenues puisque le Ministère de l’Agriculture, des Pêcheries et de l’Alimentation du Québec (MAPAQ) et le Ministère des Forêts, de la Faune et des Parcs (MFFP) travaillent actuellement à la production d’un atlas cartographique des zones de pêches qui devrait être publié en 2022. Lorsque disponible, les données de cet atlas devraient être intégrées à l'évaluation des effets cumulatifs afin de bonifier la caractérisation des activités de pêches commerciales dans la zone d'étude.

<br>

***Épaves***

Les sites de naufrage sont actuellement considérés en tant que stresseur environnemental au sein de notre évaluation. Les épaves sont toutefois également des sites archéologiques faisant partie du patrimoine québécois; ces dernières pourraient ainsi être considérées en tant que sites d'intérêts archéologiques au sein de la composante valorisée de sites d'intérêt culturels, patrimoniaux et archéologiques. Une caractérisation des sites archéologiques d'intérêt existe à travers la l'Inventaire des sites archéologiques du Québec du Ministère de la Culture et des Communications. Nous n'avons toutefois pu accéder à cet inventaire dans le cadre de notre évaluation. Il serait ainsi pertinent d'ajouter les données de cet inventaire si une mise à jour de l'évaluation des effets cumulatifs est effectuée. 


## Hotspots d'effets cumulatifs {.unlisted .unnumbered}

***Perspective*** : l'évaluation des effets cumulatifs a permis d'identifier des milieux de la zone d'étude qui sont particulièrement à risque des activités maritimes. Citons notamment les régions de Québec et du sud de l'Île d'Orléans, du lac Saint-Pierre et du chenal de navigation entre Trois-Rivières et Montréal au sein du secteur fluvial et l'embouchure de la Rivière Saguenay au sein du secteur maritime. Des évaluations subséquentes pourraient approfondir l'évaluation des effets cumulatifs en effectuant une analyse à fine échelle qui pourrait complémenter l'analyse régionale effectuée dans le cadre de ce projet pilote. 


## Scénarios de gestion {.unlisted .unnumbered}

***Perspective*** : Dans un futur rapproché, il est attendu que les pressions environnementales d'origines anthropique et naturelle continueront de s'intensifier. Considérés collectivement, les pressions croissantes suggèrent que nous serons bientôt confrontés à de nouveaux enjeux environnementaux complexes. Des approches prédictives permettant de tester des scénarios de gestion deviennent alors un atout majeur [@dube2003; @jones2016; @hodgson2019]. La méthode d'évaluation des effets cumulatifs utilisée pour ce projet pilote fournit ce type d'approche prédictive qui permet d’évaluer les risques associés aux effets de plusieurs stresseurs environnementaux. Des prédictions de changements environnementaux pourraient ainsi être incorporées à l'évaluation des effets cumulatifs. Dans le cadre d’évaluations d'effets cumulatifs, il serait ainsi possible d’explorer une gamme de scénarios visant le développement de nouveaux projets économiques au sein de la zone d'étude, dont l'accroissement du trafic maritime, et déterminer les changements pressentis au niveau des effets cumulatifs sur les composantes valorisées d'intérêt et d’offrir des recommandations pour les gestionnaires. Tester de tels scénarios permettrait d'adopter une approche analytique afin d'identifier des mesures de gestion et d'atténuation proactives; ces dernières constituent les étapes suivantes au sein de la démarche d'évaluation des effets cumulatifs présentée en introduction du présent rapport.


## Opérationnaliser les évaluations des effets cumulatifs {.unlisted .unnumbered}

***Perspective*** : L'évaluation des effets cumulatifs repose sur une quantité importante de données; cette réalité est fréquemment citée en tant que limitation majeure pour l'évaluation des effets cumulatifs [*e.g.* @jones2016; @hodgson2019]. Les données ou connaissances nécessaires sont parfois indisponibles, inaccessibles, ou inexistantes. Même lorsque les données sont disponibles, il peut être particulièrement difficile d’assembler une base de données permettant d'effectuer une évaluation à large échelle. Ces besoins croissants en données mettent en évidence le besoin de valoriser les connaissances acquises, de les structurer de façon interopérable -- *i.e.* faciliter l’union de bases de données distinctes -- de les rendre disponibles pour tous et de se doter d’infrastructures maximisant nos capacités de gestion adaptative [@reichman2011; @poisot2013; @wilkinson2016; @williams2020]. C'est avec ces réalités en tête que nous avons construit ce projet pilote à partir d'une approche transparente et reproductible permettant l'intégration aisée de nouvelles données, d'ajuster certaines portions des analyses et de régénérer l'ensemble des analyses, des figures et des tableaux du rapport. Une seconde évaluation suite à ce projet pilote pourrait ainsi construire directement à partir du travail déjà effectué. Ultimement, il pourrait être envisageable de facilement mettre à jour une évaluation dès que de nouvelles connaissances sont disponibles grâce à des outils et infrastructures permettant de reproduire le travail de façon efficace. Ce travail, qui relève davantage des sciences des données -- *data science* -- devrait être valorisé et poursuivi si une seconde phase est financée pour ce projet pilote. Adopter une telle approche contribuerait directement à la dernières étape de la démarche d'évaluation des effets cumulatifs présentée en introduction du présent rapport, *i.e.* assurer un suivi et une gestion adaptative.


## Exploration interactive des évaluations d'effets cumulatifs {.unlisted .unnumbered}

***Perspective*** : Tel que mentionné lors de la présentation des résultats de l'évaluation, l'interprétation a été limitée à de grands constats afin de simplifier les messages clés issus de ce projet pilote. Il est ainsi clair que plusieurs préoccupations des communautés locales, experts et Premières Nations n'ont pu être explorées en détail. La méthode permet toutefois d'explorer l'ensemble des combinaisons possibles de stresseurs environnementaux et de composantes valorisées. Afin de permettre ce type d'exploration, il serait pertinent de développer un outil interactif web permettant à un utilisateur de sélectionner certaines composantes valorisées et certains stresseurs afin d'explorer les détails des résultats de l'évaluation des effets cumulatifs. À la jonction entre les sciences de données et la programmation web, ce type d'outil permettrait une plus grande flexibilité pour l'exploration des résultats, mais également une meilleure expérience utilisateur. Nous avons déjà construit ce type d'outil pour les stresseurs au sein de l'estuaire et du golfe du Saint-Laurent [@beauchesne2020] : [https://david-beauchesne.shinyapps.io/edriversapp/](https://david-beauchesne.shinyapps.io/edriversapp/). Cet outil pourrait être bonifié afin d'y incorporer les composantes valorisées et l'évaluation des effets cumulatifs.



