# Acknowledgements {-}

First and foremost, we wish to thank all the participants and organizations that contributed to this pilot project by their presence at the consultation workshops that helped identify the environmental stressors and valued components selected for this study and at the series of webinars organized throughout the project. Those discussions not only helped in identifying the objectives of this project, but also guided the last two years of work for our research team. 

We wish to thank the First Nations that engaged in this study for your presence at the consultation workshops, discussions throughout the whole project with our research team, and for the data and knowledge you shared with us. Your implication was crucial to this project. We wished to engage with First Nations with humility and consideration, and it is with humility and consideration that we hope to continue engaging with First Nations in the future.

We also wish to thank all the collaborators and organisms that engaged with our team throughout the project. Your openness and willingness to share your knowledge are crucial to cumulative effects assessments and to ecosystem-based management in general; without your work, ours would be impossible. Some of those collaborators are acknowledged directly in the subsections of the [portrait of the study area](#portrait) of the report; others are identified in [appendix 2](#annexe2). This appendix lists over 60 collaborators and organizations that contributed through discussions and data, or by sharing data on open-data platforms.

We also thank members of the St. Lawrence action plan on the project *Establishing a common framework for the cumulative effects assessment of maritime activities in the St. Lawrence/Saguenay*; your comments and our discussions improved our report until the very end. We sincerely hope that our assessment will be useful to your work and that it will be a source of motivation and inspiration to continue and diversify your efforts in the St. Lawrence. 

Finally, a special thanks to Catherine Guillemette, Transport Canada, without whom the project would not exist. Simply, your work connected a remarkable network of interested parties that is diversified and invested in an integrative approach to the management of our ecosystems. More importantly, it is your ability to listen and your openness that transformed this project into an adventure with a clear starting point and a finish line left to be discovered. Few project managers possess this ability to adjust their objectives and their expectations throughout a project and we are deeply grateful for the opportunity we had to work closely with you. We can only hope that you will continue working on unifying projects; the social and environmental challenges of tomorrow will need ambassadors like you! 

