### Qualité de l'eau

La qualité de l’eau a été identifiée en tant que composante valorisée lors des différents ateliers de mobilisation visant leur identification. La qualité de l’eau est toutefois affectée par une suite de facteurs multiples incluant l’agriculture, la pollution atmosphérique, les rejets d’égouts [@ref]. Au sein du secteur fluvial, la qualité de l'eau semble influencée principalement par l'occupation terrestre; la proximité d'une grande ville ou les activités agricoles affectent directement la qualité de l'eau [@ref]. La qualité de l'eau est également grandement affectée par les terres agricoles très présentes à l'île d'Orléans et la rive sud [@ref]. Les activités maritimes ne sont généralement pas citées comme une source potentielle significative de pollution ayant un effet sur la qualité de l'eau [@ref].

Bien que la qualité de l'eau soit une préoccupation valide, il est difficile de relier des mesures de qualité de l’eau spécifiquement aux activités maritimes. En tant que tel, nous considérons qu'une caractérisation de la qualité de l'eau dans le cadre d'une évaluation sectorielle des effets cumulatifs centrée sur les activités maritimes risquerait d'attribuer une responsabilité à un secteur d'activités qui ne lui revient sans doute pas.

Afin d’adresser cette problématique, nous avons plutôt décidé d’adopter une approche alternative afin de considérer les risques pour la qualité de l’eau associés aux activités maritimes. Dans leurs travaux, @halpern2019 ont plutôt considéré la qualité de l’eau en tant que stresseurs de pollution maritime. Ce stresseur était décrit en combinant les différents stresseurs individuels reliés aux activités maritimes, soit la navigation et les activités portuaires dans leur cas. Nous avons ainsi opté pour une approche similaire et considérons la pollution maritime en tant que stresseurs environnementaux en remplacement de la composante valorisée de qualité de l’eau. Veuillez vous référer à la section sur les stresseurs environnementaux pour la description du stresseur pollution maritime.



<br/>
