## Collecte et gestion des données

### Collecte des données

Puisque ce projet pilote ne visait aucune collecte de nouvelles données, le portrait présenté représente une veille des connaissances actuelles permettant de caractériser les activités maritimes et les composantes valorisées au sein de la zone d'étude. La disponibilité et l'accessibilité des données a ainsi guidé le travail accompli. La collecte des données a été effectuée en collaboration avec les différentes parties impliquées aux projet ainsi qu'avec la collaboration et le soutien de Transports Canada et les membres du projet porté par le Plan d’action Saint-Laurent.

La collecte des données a débuté par l'envoie d'une liste à annoter à divers experts et parties impliquées au projet. Cette liste était constituée de sous-catégories stresseurs environnementaux et de composantes valorisées. Les participants étaient invités à identifier toutes bases de données connues permettant d'effectuer une caractérisation des stresseurs et des composantes valorisées au sein de la zone d'étude, et d'identifier toutes autres sous-catégories ou bases de données jugées pertinentes au projet. Nous avons ensuite colligé les commentaires et suggestions et avons commencé les démarches en vue de collecter les données pertinentes à l'évaluation des effets cumulatifs.

Lorsque possible, les données ouvertement accessibles à partir de portails de données tels les plateformes de partage fédérale [*Gouvernement ouvert*](https://open.canada.ca/fr) et provinciale [*Données Québec](https://www.donneesquebec.ca/), ainsi que les ressources disponibles par l'[*Observatoire Global du Saint-Laurent*](https://ogsl.ca/fr/accueil/) (OGSL) ont été priorisées. À cet égard, des recherches ont été effectuées sur ces plateformes afin d'identifier des données pertinentes n'ayant pas été signalées par la liste partagée précédemment. En priorisant les données ouvertes, il sera plus aisé de reproduire et mettre à jour l'évaluation effectuée par ce projet pilote. L'[annexe 1](#annexe1) présente l'ensemble des données qui ont été considérées pour l'évaluation. Les données y sont décrites et les données retenues pour l'évaluation y sont identifiées. Les données qui n'ont pas été retenues ont été conservée afin de documenter l'ensemble des données qui ont été explorées pour l'évaluation. Les données non incluses ont été laissées de côté parce qu'elles étaient couvertes par d'autres bases de données sélectionnées ou parce qu'elles n'adressaient pas un objectif spécifique de l'évaluation.

Une attention particulière a également été attribuée aux connaissances détenues par des experts disciplinaires, ainsi que par les divers collaborateurs participants. Nous avons ainsi échangé directement avec des personnes ressources afin de réviser les différentes sections du portrait de la zone d'étude caractérisant les stresseurs environnementaux et les composantes valorisées. Les personnes ressources ayant contribué à la révision de ces sections sont d'ailleurs remerciées spécifiquement au début des sections auxquelles elles ont contribué. Une liste des personnes ou organismes ressources pour ce projet est disponible à l'[annexe 2](#annexe2).   

La collaboration avec les Premières Nations a également été un élément important du projet afin d'assurer la valorisation des savoirs autochtones et des préoccupations des Premières Nations présentes au sein de la zone d'étude. Nous avons ainsi échangé avec des représentants des Premières Nations participantes en vue d'obtenir une caractérisation spatiale de sites d'intérêt culturels, patrimoniaux et archéologiques. Davantage de détails sont disponibles à la section présentant les sites d'intérêt culturels, patrimoniaux et archéologiques.


### Gestion des données et reproductibilité

La gestion des bases de données visait à assurer la transparence et la reproductibilité de l'évaluation des effets cumualtifs. Nous basons notre approche sur les principes <a href="https://ogsl.ca/fr/principes-fair" target="_blank"><i>FAIR</i></a> (Findable, Accessible, Interoperable, Reusable), qui visent à s’assurer que les données utilisées soient découvrables, accessibles, interopérables et réutilisables. Nous utilisons ainsi des outils de programmations, notamment le langage <a href="https://www.r-project.org/" target="_blank"><i>R</i></a>[^r]. L’utilisation d’outils de programmation, à l’instar de logiciels comme <a href="https://www.arcgis.com/index.html" target="_blank"><i>ArcGIS</i></a>[^arc], offre plusieurs avantages. Ils offrent une grande souplesse permettant l’intégration de changements ou de nouvelles considérations très rapidement sans devoir refaire plusieurs étapes d’un processus complexe. Cette souplesse ne se limite pas aux analyses, puisque l’ensemble des étapes d’un projet, de l’intégration des données brutes à la production de rapports, peuvent être intégrées et ainsi facilement modifiées. Il devient alors aisé d’intégrer des commentaires ou de nouvelles recommandations suite à des processus de mobilisation, par exemple.

Nous avons également utilisé <a href="https://github.com/" target="_blank"><i>GitHub</i></a>[^git], un outil de contrôle de version qui permettra la documentation, le contrôle de la qualité et l’historique du développements et des modifications des éléments de programmation pertinents à l’ensemble du projet. Nous avons créé une organisation nommée <a href="https://github.com/EffetsCumulatifsNavigation" target="_blank"><i>EffetsCumulatifsNavigation</i></a>. L'ensemble des rapports rédigés et des séminaires offerts pendant le projet pilote y sont disponibles. Un dépôt public intitulé <a href="https://github.com/EffetsCumulatifsNavigation/ceanav" target="_blank"><i>ceanav</i></a> fait office de *compendium de recherche* et constitue le coeur de l'évaluation; un *compendium de recherche* est une collection de l'ensemble des parties d'un projet de recherche incluant le texte, les figures, les données et le code assurant la reproductibilité de l'étude. Une description détaillé de la structure du *compendium de recherche* de l'évaluation est disponible à l'[annexe 3](#annexe3) et sur la page web du dépôt GitHub <a href="https://github.com/EffetsCumulatifsNavigation/ceanav" target="_blank"><i>ceanav</i></a>.

Sans inclure les données directement, le *compendium de recherche* de l'évaluation contient l'ensemble des ressources permettant d'accéder aux données brutes et de les transformer. Il contient également le code permettant de caractériser les stresseurs environnementaux et les composantes valorisées, d'effectuer les analyses, les figures, les tableaux et le rapport final. Seules les données à nature sensibles pour lesquelles des ententes de confidentialité ont été signées demeurent inaccessibles; ces dernières sont toutefois cataloguées au sein du rapport et des documents accompagnateurs afin qu'un utilisateur ou un lecteur puisse connaître le type et la provenance des données utilisées au sein des analyses, ainsi que les personnes ressources à contacter en vue d'obtenir davantage d'informations sur les données utilisées. Les données intégrées au sein de la grille d'étude et permettant d'effectuer l'évaluation des effets cumulatifs sont quant à elles ouvertement disponibles à travers le dépôt principal du projet pilote <a href="https://github.com/EffetsCumulatifsNavigation/ceanav" target="_blank"><i>ceanav</i></a>; nous travaillons également avec l'OGSL afin de les rendre disponibles sur leur portail.

```{r}
meta <- read.csv("../data/data-metadata/data_summary.csv")
```

Les bases de données qui ont été considérées pour l'évaluation sont identifiées par un identifiant unique de la forme `####` pour chaque base de données considérées et qui est disponible à l'[annexe 1](#annexe1). Par exemple, la base de donnée `0001` correspond à un inventaire de la zostère marine (*Zostera marina*) pour la Baie James, la Baie des Chaleurs, l'estuaire et le golfe du Saint-Laurent [@mpo2009]. Ces identifiants uniques sont utilisés afin d'identifier, directement sur les figures, les bases de données qui ont été utilisées pour caractériser les catégories de stresseurs environnementaux et de composantes valorisées présentées aux sections \@ref(strportrait) et \@ref(cvportrait); la liste des identifiants uniques peut être visualisée dans la marge inférieure droite de chaque figure. De plus, toutes les données et métadonnées incluses au *compendium de recherche* de l'évaluation utilisent ces identifiants uniques afin de faire référence aux bases de données considérées. Au total, `r nrow(meta)` bases de données ont été considérées pour l'évaluation et sont accessibles à travers le *compendium de recherche*; de ce nombre, `r sum(meta$ana == "X", na.rm = TRUE)` ont été utilisées pour effectuer l'évaluation des effets cumulatifs des activités maritimes sur les composantes valorisées sélectionnées. Consultez l'[annexe 1](#annexe1) pour plus de détails sur ces bases de données. Tout comme pour les données, les différents organismes et experts consultés pour ce projet, ou dépositaires de bases de données ouvertes utilisées, sont identifiés par un identifiant unique de la forme `####` qui est disponible à l'[annexe 2](#annexe2).

[^r]: R est un logiciel libre destiné aux statistiques, la science des données et les graphiques (https://www.r-project.org/)
[^arc]: ArcGIS est une suite de logiciels d'information géographique (SIG) développés par la société américaine Esri (https://www.arcgis.com/index.html)
[^git]: GitHub est un service web d'hébergement et de gestion de développement de logiciels utilisé par plus de 40 millions d'utilisateurs partout à travers le monde (https://github.com/).
