## Projets connexes

### Projet Emphase

L’objectif du projet EMPHASE (INRS : http://lhe.ete.inrs.ca/projet-emphase/) est de doter les instances décisionnelles d’un outil performant et facile d’utilisation permettant de concilier l’usage de la navigation avec les enjeux de développement durable. Il est composé notamment d’un volet sur l’analyse des effets et des perceptions des navigations (plaisance et commercial) sur les érosions de berges et d’un volet sur la modélisation 3D pour le développement d’un outil de mesure permettant de valider avec précision l’effet de batillage. La méthodologie s’appuie sur des travaux de terrains, des essais de laboratoire et des simulations numériques.  Spécialiste en hydrodynamique navale et transport des sédiments, le professeur Pham Van Bang et son équipe étudieront la physique derrière le phénomène d’érosion des berges afin de caractériser les effets du passage des bateaux commerciaux et de plaisance. Le travail se fera principalement à travers des simulations numériques et de la recherche sur le terrain. En plus de l’aspect dynamique de l’érosion, le projet comporte un volet sociojuridique. Pour cet aspect du projet, le professeur Damien Pham Van Bang collaborera avec des chercheurs de l’Université de Montréal et de l’Université de Sherbrooke, qui vont analyser la perception du risque de l’érosion des berges et étudier le cadre réglementaire et législatif à l’échelle du Québec et de la France



### Projet Érosion

 Ce projet est issue du Volet fluvial de la mesure 2.6 du Plan d’action sur les changements climatiques (PACC) 2013-2020 : « Soutien aux municipalités situées le long du Saint-Laurent confrontées aux aléas d’inondation et d’érosion ».

Les objectifs du projet ÉROSION sont :

1. Inventorier et rassembler les informations provenant des études et des données géospatiales existantes;
2. Segmenter et caractériser les types de berges;
3. Documenter les processus géomorphologiques et hydroclimatiques;
4. Réaliser des consultations et ateliers; et
5. Identifier les secteurs sensibles.

L’APM a pris part le 4 octobre 2019 à un premier atelier définissant le « portrait actuel des connaissances et l’identification des besoins des communautés » et un second atelier sur la méthodologie et les résultats du projet lequel a eu lieu le 31 janvier 2020 à Montréal. Le volet fluvial s’appuie sur une collaboration étroite entre le MELCC, Ouranos, l’Université Laval (Patrick Lajeunesse et J.F. Bernier) et la Table de concertation régionale Haut-St-Laurent Grand Montréal (TCR HSL-GM) dont l’APM est membre de son Conseil stratégique. À souligner que lors de la rencontre, l’équipe de projet a indiqué que des démarches étaient en cours avec le MELCC pour poursuivre l’étude au-delà des trois premiers objectifs par des travaux de terrain pour mieux mesurer et comprendre la part des stresseurs (anthropiques et naturels) et l’impact sur l’érosion des berges.


### Caractérisation des berges de la partie fluviale du Saint-Laurent

Le projet « Caractérisation des berges de la partie fluviale du Saint-Laurent » de l’Université Laval vise à caractériser les berges et à constituer une base d’information essentielle pour évaluer les risques liés à l’érosion en milieu fluvial. Il vise également à soutenir les intervenants clés de l’aménagement du territoire de ce milieu dans le choix des mesures qui assureront une plus grande résilience et une protection adéquate des communautés riveraines et de l’environnement naturel à long terme. Le projet établit une base de données géospatiales constituant un temps de référence pour les futurs suivis à haute résolution sur la mobilité de la ligne de rivage du fleuve Saint-Laurent.

Instigateur : Patrick Lajeunesse

Les principaux produits cartographiques disponibles depuis le printemps 2020 sont :

- Cartographie des types de côtes ainsi que des unités hydrosédimentaires, soit les types de côtes, segments des terrasses de plages et des marais, leur artificialisation (naturelle ou avec ouvrage de protection), l’état des infrastructures de stabilisation, l’état de la côte (végétalisée, partiellement stable, active, etc.). La caractérisation est fournie sous forme de cartographie et de base de données dans un système d’information géographique.
- Répertoire des secteurs les plus vulnérables à l’érosion sous forme de fiches qualitatives imagées, exposant les principaux processus géomorphologiques, fluviaux (courants, glace, etc.) et humains associés à l’érosion des berges pour certains secteurs névralgiques afin de mieux représenter la dynamique locale (type de côte, état de la côte, type de dépôt de surface, etc.).
