## Constats généraux

Nous présentons au sein de cette section les constats généraux issus de l'évaluation des effets cumulatifs en points de forme. Des constats additionnels pourraient être faits en explorant davantage les résultats obtenus et nous invitons le lecteur à s'attarder à la section \@ref(resultats) du rapport pour davantage d'informations et à explorer les figures qui y sont présentées plus en détails.

<br/>

- **Distribution des stresseurs environnementaux issus des activités maritimes**
  - L'ensemble de la zone d'étude est exposé aux stresseurs environnementaux;
  - Les grandes villes portuaires et la voie navigable sont particulièrement exposées;
  - La navigation et la pollution maritime sont les stresseurs les plus répandus.

<br/>

- **Distribution des composantes valorisées**
  - L'ensemble de la zone d'étude est couverte par une ou plusieurs composantes valorisées;
  - Les milieux côtiers présentent une diversité plus importante de composantes valorisées;
  - La région du lac Saint-Pierre est particulièrement riche en composantes valorisées;
  - Dans le secteur maritime, l'embouchure de la Rivière Saguenay présente la plus grande diversité de composantes valorisées.

<br/>

- **Distribution des effets cumulatifs**
  - L'entièreté de la zone d'étude est affectée par les effets cumulatifs des activités maritimes;
  - Les effets cumulatifs sont particulièrement intenses et concentrés au sein du secteur fluvial; les effets y sont plus intenses dans les régions de Québec et du sud de l'Île d'Orléans, du lac Saint-Pierre et du chenal de navigation entre Trois-Rivières et Montréal;
  - Les effets cumulatifs sont plus diffus au sein du secteur maritime; les effets les plus intenses sont situés à l'embouchure de la Rivière Saguenay.

  <br/>

- **Stresseurs environnementaux les plus importants**
  - La navigation et la pollution maritime ont les effets les plus importants à l'échelle régionale puisqu'ils sont les stresseurs les plus répandus au sein de la zone d'étude;
  - Les pêches commerciales ont des effets importants sur un nombre limité de composantes valorisées considérées, comme les gisements coquilliers et certains sites d'intérêt culturels, patrimoniaux et archéologiques;
  - Les sites d'ancrage, les déversements accidentels et les activités de dragage ont des effets localisés sur certaines composantes valorisées. Ces stresseurs, bien que moins répandus, ajoutent leurs effets à ceux de la navigation et de la pollution maritime et sont généralement présents au sein des milieux qui sont les plus affectés par les effets cumulatifs (*e.g.* lac Saint-Pierre).

  <br/>

- **Composantes valorisées les plus affectées**
  - Les sites d'intérêt culturels, patrimoniaux et archéologiques sont les plus exposés aux effets des activités maritimes. Bien que ce résultat soit attendu considérant leur vulnérabilité élevée, ce constat demeure important et témoigne du chevauchement important entre les sites d'intérêt pour les Premières Nations et les activités maritimes dans la zone d'étude;
  - Les sites d'intérêt des Premières Nations situés au sein du secteur fluvial sont davantage exposés aux effets cumulatifs de la navigation dû à la concentration des effets au sein de ce milieu;
  - L'intégrité des berges au sein du secteur fluvial est particulièrement affectée par la navigation, et ce particulièrement au sein du lac Saint-Pierre;
  - Les habitats considérés sont affectés par une diversité importante de stresseurs environnementaux et il y a une diversité importante au niveau des effets totaux prédits entre les différents types d'habitats
  - Bien que les mammifères marins semblent moins affectés que les autres composantes valorisées par les effets cumulatifs des activités maritimes, il est important de considérer la large répartition spatiale de ces espèces au sein du secteur maritime de la zone d'étude. Les effets cumulatifs sur les mammifères marins sont plutôt localisés au niveau de l'embouchure de la Rivière Saguenay.

  <br/>

- **Régions administratives les plus affectées**
  - Les régions administratives du secteur fluvial sont les plus affectées par les effets cumulatifs des activités maritimes, un constat particulièrement important pour la Montérégie;
  - La Côte Nord est la région administrative la plus affectée au sein du secteur maritime.
