### Dragage

```{r dragage_setup, echo = FALSE}
meta <- read_yaml("../data/data-metadata/int_st_dragage.yml")
```
La voie navigable du Saint-Laurent a historiquement été draguée partout où la profondeur naturelle ne permettrait pas le passage sécuritaire des bateaux. Entre Montréal et Cap Gribane, la voie navigable est d'une longueur totale d'environ 340 km et elle a été artificialisée sur une longueur d'environ 210 km afin d'y assurer une navigation sécuriaire [@ghb2019]. Sur cette longueur, une certaine proportion doit être draguée à intervalle régulier -- *i.e.* dragages d'entretien -- dû à la dynamique sédimentaire des milieux.

Une caractérisation historique des activités de dragage de capitalisation -- *i.e.* dragage visant à approfondir et élargir la voie de navigation -- est décrite par @ref.

Dans le cadre de notre étude, l'emphase a plutôt été mise sur les activités de dragage contemporaines pour la période entre `r meta$dataDescription$temporal$start` et `r meta$dataDescription$temporal$end`.


Important de noter que les volumes totaux dragués ne correspondent pas aux volumes totaux déposés puisque certaines activités de dragage ont des dépôts terrestres et n'ont ainsi pas été comptabilisés.

> En termes simples, le chenal de navigation a été dragué (ou artificialisé) partout (entre Montréal et Cap Gribane) où la profondeur naturelle ne permettait pas d’avoir la profondeur voulue, sur la largeur voulue pour un passage sécuritaire des bateaux dans les différentes phases successives de dragage de conception/amélioration de la voie navigable. Je ne sais pas combien de km ont été « artificialisés », mais j’imagine que la responsable de la GCC pourrait te donner cette info. La profondeur naturelle du fleuve à certains endroit est suffisante, ce qui explique que les zones ayant dû être draguées ne sont pas nécessairement continues. Il y a eu quelques phases d’amélioration (lire approfondissement/élargissement par rapport au design original) de la voie navigable, dont je ne connais pas les dates, principalement en raison de l’agrandissement de la taille des bateaux et de l’augmentation du trafic maritime dans le fleuve avec les années. Quand on parle d’approfondissement de la voie de navigation, on appelle ça du dragage de capitalisation.

> L’aspect qui est traité dans les rapports de la GCC est relié plutôt au dragage d’entretien (respect du design actuel (profondeur et largeur minimum), sans approfondir) de la voie de navigation, car certains secteurs sont plus sujets à l’ensablement et doivent être entretenus selon une fréquence variable. Je n’ai pas les chiffres non plus (distances en kilomètres entretenus, fréquence…) mais les rapports ou u contact à GCC peux certainement te renseigner à ce sujet.
