# Vulnérabilité {#vulnerabilite}

La méthode proposée requiert une évauation relative de la vulnérabilité des composantes valorisées aux stresseurs environnementaux considérés. Ce type de connaissance peut être particulièrement difficile à obtenir: des équipes de recherche entières peuvent s’intéresser à la vulnérabilité d’une seule composante valorisée à un seul facteur de stress, tel que la vulnérabilité des mammifères marins au bruit sous-marin. Bien que la vulnérabilité de certaines composantes valorisées à certains facteurs de stress soit bien documentée et permettrait une évaluation robuste des impacts environnementaux individuels, ce type de connaissance est rarement – voire jamais – disponible pour l’ensemble des combinaisons “composantes valorisées-facteurs de stress”; c’est pourtant une nécessité pour effectuer une évaluation d’effets cumulatifs.

Une approche qualitative faisant appel à l’opinion d’experts et/ou à la recherche bibliographique est ainsi généralement utilisée afin de générer une matrice de scores de vulnérabilité relative noralisée entre 0 -- insensible -- et 1 -- très sensible -- pour les combinaisons de composantes valorisées et de facteurs stress; ces processus d'évauation qualitatifs sont basés sur une série de critères tel la résilience des composantes valorisées à un stresseur et la fréquence des stresseurs sur le système  [e.g. @teck2010; @halpern2013; @refCSAS?]. Considérant la diversité des composantes valorisées intégrées à cette évaluation, il n'est toutefois pas possible de développer une approche unique englobant l'ensemble de ces dernières. En effet, différents critères seront important pour déterminer la vulnérabilité de la baleine bleu à la navigation que celle d'une frayère. Une approche différente a ainsi été adoptée pour les différentes composantes valorisées considérées.
