### 0008 : Milieux sableux Saint-Laurent {-}

<!-- -------------------------------------------------- -->
**Description** : Atlas des milieux côtiers d’intérêt pour la conservation dans l’estuaire et le golfe du Saint-Laurent

<!-- -------------------------------------------------- -->

  **Hyperlien** : [https://catalogue.ogsl.ca/fr/dataset/0a232214-05cc-438a-b914-6a8b53ac184e](https://catalogue.ogsl.ca/fr/dataset/0a232214-05cc-438a-b914-6a8b53ac184e)


<!-- -------------------------------------------------- -->

  **Couverture temporelle** : 2016 - 2016



<!-- -------------------------------------------------- -->
**Contact** :


  - 0008 : *Plan d'action Saint-Laurent*



<!-- -------------------------------------------------- -->
**Citation** :


  - Plan d'action Saint-Laurent. (2020). Atlas des milieux côtiers d’intérêt pour la conservation dans l’estuaire et le golfe du Saint-Laurent (Version 1.0) [Milieux sableux]. Observatoire Global du Saint-Laurent. https://doi.org/10.26071/OGSL-0A232214-05CC

  - JOBIN, B., L. GRATTON ET P. DESAUTELS. 2019. Atlas des milieux côtiers d’intérêt pour la conservation dans l’estuaire et le golfe du Saint-Laurent – Rapport méthodologique. Environnement et Changement climatique Canada et ministère de l’Environnement et de la Lutte contre les changements climatiques, Plan d’action Saint-Laurent, Québec, 93 p.




<!-- -------------------------------------------------- -->




<hr>
<br>
